### ISSUE TITLE
能否增加英语引导输入功能？

### ISSUE THREAD

**Issue by jdjxk** [ksqsf/rime-moran#103]
类似日语 ojp 引导输入，以 oen 引导

**Comment by ksqsf** [comment]
这个不难实现，没有增加是因为感觉用不到（每增加一个组件就会造成性能的一点损耗，所以默认选择是不加），所以想问一下有没有什么使用场景？

日语需要引导是因为有时需要输入单个假名，比如「あ」，输入 a 再在列表里找非常慢。英语按我理解并不存在这个问题，不管多短只要回车就能上屏了。

**Comment by jdjxk** [comment]
当开启英语混输时，辅筛模式下，如输入ui，hk等短编码，会出现UI，HK单词出现在首选的情况，干扰比较大，不过整句模式并未出现此类候选。

**Comment by ksqsf** [comment]
感谢反馈，已修复。

**Comment by jdjxk** [comment]
感谢，完美解决问题
