### ISSUE TITLE
使用整句输入的时候断词有些奇怪

### ISSUE THREAD

**Issue by DehanLUO** [ksqsf/rime-moran#107]
我想键入“月落屋啼灀满天”，这里我故意想打错两个字。实际键入ytlowutiudmjtm后，Tab在yt后键入o找到“月”，再Tab在lo后键入c找到“落”，再Tab在wu后键入u找到“屋”。此时我预期的想法是再Tab在ti后键入k找到“啼“。但实际此时Tab后光标定位到tiu之后，把灀(shuàng,ud)的声母直接划进来了。

![screenshot](https://github.com/user-attachments/assets/2e5516d7-5594-4a34-9393-b12b207d89e9)

**Comment by ksqsf** [comment]
感谢汇报！这是一个已知的问题，我认为是 librime 的 bug。之后我会仔细分析一下。

**Comment by ksqsf** [comment]
就 issue 中的这句话是预期现象。这是因为 tiudmjtm 会被优先切分成 tiu dmj tm 题錪天，所以向前跳转会跳到 tiu 之后。（之前提到的 librime bug 是因为我偶尔会碰到一些跳转完全失灵的情况，之前没记录具体的输入所以只能等下一次碰到了。）

有一些 hack 可以解决该问题：

1. 增加一个纯双拼的 translator 并优先放在前面。
2. 修改 librime 对 segment 的处理，在首次 edit 后记录以前的 span，不再重新计算。

第二个办法成本过高，暂不考虑。第一个办法则会造成部署时间增加（需要添加一个纯双拼的辅助方案和对应的 spelling algebra）也会造成性能下降，暂时没想好要不要这么做。

目前来说，碰到这种情况时，我还是推荐首先使用 tab 和方向键（或 Ctrl-f 和 Ctrl-b）来微调一下。尽管会碰到这种情况，但是碰到的几率也不是很高。

**Comment by liangkaichun** [comment]
> 就 issue 中的这句话是预期现象。这是因为 tiudmjtm 会被优先切分成 tiu dmj tm 题錪天，所以向前跳转会跳到 tiu 之后。（之前提到的 librime bug 是因为我偶尔会碰到一些跳转完全失灵的情况，之前没记录具体的输入所以只能等下一次碰到了。）
> 
> 有一些 hack 可以解决该问题：
> 
> 1. 增加一个纯双拼的 translator 并优先放在前面。
> 2. 修改 librime 对 segment 的处理，在首次 edit 后记录以前的 span，不再重新计算。
> 
> 第二个办法成本过高，暂不考虑。第一个办法则会造成部署时间增加（需要添加一个纯双拼的辅助方案和对应的 spelling algebra）也会造成性能下降，暂时没想好要不要这么做。
> 
> 目前来说，碰到这种情况时，我还是推荐首先使用 tab 和方向键（或 Ctrl-f 和 Ctrl-b）来微调一下。尽管会碰到这种情况，但是碰到的几率也不是很高（尽量不要打太长的句子），还可以接受。也欢迎分享您的想法。

这种使用方式，应该用辅筛模式啊。直接辅码才用魔然整句吧。

**Comment by DehanLUO** [comment]
> > 就 issue 中的这句话是预期现象。这是因为 tiudmjtm 会被优先切分成 tiu dmj tm 题錪天，所以向前跳转会跳到 tiu 之后。（之前提到的 librime bug 是因为我偶尔会碰到一些跳转完全失灵的情况，之前没记录具体的输入所以只能等下一次碰到了。）
> > 有一些 hack 可以解决该问题：
> > 
> > 1. 增加一个纯双拼的 translator 并优先放在前面。
> > 2. 修改 librime 对 segment 的处理，在首次 edit 后记录以前的 span，不再重新计算。
> > 
> > 第二个办法成本过高，暂不考虑。第一个办法则会造成部署时间增加（需要添加一个纯双拼的辅助方案和对应的 spelling algebra）也会造成性能下降，暂时没想好要不要这么做。
> > 目前来说，碰到这种情况时，我还是推荐首先使用 tab 和方向键（或 Ctrl-f 和 Ctrl-b）来微调一下。尽管会碰到这种情况，但是碰到的几率也不是很高（尽量不要打太长的句子），还可以接受。也欢迎分享您的想法。
> 
> 这种使用方式，应该用辅筛模式啊。直接辅码才用魔然整句吧。

刚刚参考使用说明试了下辅筛模式，确实符合我的使用习惯。还省去了按触发器`Tab`。
