### ISSUE TITLE
[请益] 英语混输是否有可能支持大写字母开头的输入？

### ISSUE THREAD

**Issue by Konjac-XZ** [ksqsf/rime-moran#109]
冒昧求教。我输入一些词汇的时候会下意识按一下大写（比如：OpenSSL），这个时候我会觉得如果有个提示未尝不是好事。但是当我直接在 `moran_english.dict.yaml` 当中把原有的小写码表转换一遍附带上之后，会产生问题：

```
Running duration (h:mm:ss): 0:00:03
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
E20241019 17:02:41.704876  4540 deployment_tasks.cc:374] dictionary 'moran_english' failed to compile.
```

我对于词条进行了一遍筛选，应该没有重复的问题。同时，在 `moran_english.schema.yaml` 当中，还有这样的注释：

```
speller:
  alphabet:     # 使該方案支持大寫拉丁字母輸入
    "zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA"
  initials:
    "zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA"
  algebra:
    __patch:
      - moran:/algebra/user_force_top?
      - moran:/algebra/user_force_bottom?
```

这个“支持大写拉丁字母输入”让我感到困惑。希望各位赐教。

**Comment by ksqsf** [comment]
可以实现：

![CleanShot 2024-10-19 at 12 56 42@2x](https://github.com/user-attachments/assets/f16fad0a-8c91-4590-bd32-62671162aa5e)

需要注意的是，需要在 **实际使用** 的 schema 的 alphabet 中增加大写字母，比如设置 moran.schema.yaml 中的 alphabet，就可以在「魔然」方案中使用大写字母开头的编码了。

![CleanShot 2024-10-19 at 12 59 11@2x](https://github.com/user-attachments/assets/1f5d6571-a70e-462b-8f01-631194d034ce)

至于 moran_english 词典编译错误我在本地没有复现，建议检查一下自己修改的格式是否正确。

PS，这个建议挺好的，我直接增加到配置中了，感谢 :)

**Comment by Konjac-XZ** [comment]
非常感谢！
