### ISSUE TITLE
半角符号的输入有异常，最新版是做了什么调整吗？

### ISSUE THREAD

**Issue by liangkaichun** [ksqsf/rime-moran#110]
更新了最新的actions版本，之前可以直接输入上屏的半角符号，现在不能直接上屏了，但又不是全部符号有这个问题。配置如下：
punctuator/half_shape:
    ',' : '，'
    '.' : '。'
    '<' : '《'
    '>' : '》'
    '/' : '/'
    '?' : '？'
    ';' : '；'
    ':' : '：'
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : '、'
    '|' : '|'
    '`' : '`'
    '~' : '~'
    '!' : '！'
    '@' : '@'
    '#' : '#'
    '%' : '%'
    '$' : '¥'
    '^' : '……'
    '&' : '&'
    '*' : '*'
    '(' : '（'
    ')' : '）'
    '-' : '-'
    '_' : ——
    '+' : '+'
    '=' : '='
    '[' : '【'
    ']' : '】'
    '{' : '「'
    '}' : '」'
在default.custom.yaml 增加了上面的内容，之前的版本都生效的。
但现在上面符号的部分符号就不能直接上屏，而是会弹出候选框，比如+、-、= 之类的。可是、就可以直接上屏。
<img width="208" alt="infoflow 2024-10-30 09-46-31" src="https://github.com/user-attachments/assets/f414abdf-c0f7-4fb3-82d1-7ca1f3073200">
<img width="246" alt="infoflow 2024-10-30 09-46-20" src="https://github.com/user-attachments/assets/7805a16f-d6d6-420d-9aac-33cc42d3c07c">
<img width="248" alt="infoflow 2024-10-30 09-46-09" src="https://github.com/user-attachments/assets/eb9e7fe7-dc0f-4c38-aab2-e24043c1de63">

**Comment by ksqsf** [comment]
感谢汇报！我也在最新 Action 版本上复现了该问题。这个问题是最近引入的 `echo_translator` 导致的。在修复该问题之前，注释掉方案中的 `echo_translator` 即可恢复正常。

**Comment by ksqsf** [comment]
TL;DR：最终决定回滚 commit 14c41e881d4b11c001492b445f584c084900bcfe 作为 fix。

详细说明：

#109 中引入的大写混输功能造成了比较严重的问题：如输入 D 空格会上屏 DJ，这至少我自己相当不习惯。

引入 echo_translator 是想解决上述问题。但是遗憾的是 echo_translator 不仅不能完全解决该问题（只在无其他候选时才 echo），还会引入新的问题：在输入 - 时，会额外输出一个 -，最后 uniquifier 会将两个 - 合并成一个候选，但导致候选类型从 punct 变为了 uniquified，使得自动上屏失效：

https://github.com/rime/librime/blob/aaaaaec3/src/rime/gear/punctuator.cc#L58

要解决这个问题需要修改 librime：

1. 让 punctuator 调用 GetGenuineCandidate 取被合并的第一个候选类型。
2. 让 echo_translator 带上 tag 参数，允许我只在 abc tag 上 echo （从而跳过 punct）。

但是改 librime 需要让用户等很久才能用上。所以我用 Lua 写了个 translator 来解决回显和英语造词问题。但是又引入了更多问题，实在是感觉不值当了。回头想想，这一切麻烦源于我非要用空格打大写字母，只要坚持用回车上屏英语就没有任何问题。所以我决定 revert 掉之前的修改，并且也不引入新的 Lua 组件，而是改一下自己的使用习惯。：）
