### ISSUE TITLE
english pattern 移入 recognizer_secondary 导致英语混输失效

### ISSUE THREAD

**Issue by jdjxk** [ksqsf/rime-moran#112]
只能把 english: '^[A-Za-z]{4}[A-Za-z]*' 添加回 recognizer

**Comment by ksqsf** [comment]
破案了，本功能依赖于 https://github.com/rime/librime/pull/691 ，而目前尚未有发布了的 librime 搭载该功能。我本地安装的是 master 版本的 librime 所以没发现。我稍后会 revert 掉这个修改。

**Comment by ksqsf** [comment]
如果有人在使用最新 librime 可以使用如下 patch 恢复该功能：
```yaml
patch:
  english/tag: english
```
