### ISSUE TITLE
提一点小感想

### ISSUE THREAD

**Issue by samuelwander** [ksqsf/rime-moran#114]
感觉魔然挺强大的，里面还有py文件之类的，在别的方案基本没见过。几次想用魔然，但是都没坚持下去，因为本人不大懂技术，开发者的方案内容写的对于我们小白来说还是挺高深的，注释也比较少，所以想改动就很困难。但不妨碍我觉得魔然是个很厉害的方案。最后祝开发者各方面越来越好！

**Comment by ksqsf** [comment]
谢谢。如果有问题可以开issue或讨论。魔然基本上完全遵循了Rime的规范，一般情况下简单的配置可以直接参考其他Rime教程。
