### ISSUE TITLE
符号候选问题

### ISSUE THREAD

**Issue by samuelwander** [ksqsf/rime-moran#115]
大佬，我有一个问题，就是我在用虎码输入时，候选总是存在？之类的符号，以及～这样的辅助码提示符，请问这两个问题特别是？这种符号该怎么取消？
找了很久没找到，希望大佬能帮我解答一下，感激不尽！

**Comment by ksqsf** [comment]
提问建议提供截图等，我不知道你说的符号是什么，所以下面都是瞎猜回答的。魔然内置的虎码方案没有这些符号。

![image](https://github.com/user-attachments/assets/645c7fca-0986-4799-a5ed-04f1cfc9cac4)

`~abc` 叫逐码提示。关闭方法：

```
patch:
  translator/preedit_format:
    - xform/.*//
```

候选存在「？」之类的符号应该是次选快符，需要从码表文件里删掉。不会的话可以咨询虎码QQ群。
