### ISSUE TITLE
鼠须管下，这些显示成问号的单字该如何处理才能显示正常？

### ISSUE THREAD

**Issue by liangkaichun** [ksqsf/rime-moran#14]
鼠须管下，这些显示成问号的单字该如何处理才能显示正常？
<img width="233" alt="infoflow 2023-09-11 09-49-49" src="https://github.com/ksqsf/rime-moran/assets/3862788/2cd7a923-0133-469a-b552-4f0bba456865">

**Comment by liangkaichun** [comment]
另外，输入词组，辅助码该如何能优先匹配词组首字，而不是尾字？

**Comment by ksqsf** [comment]
这些是超集字，需要安装对应字体才可以显示，如[天珩全字库](http://cheonhyeong.com/Simplified/download.html)。

<img width="232" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/b08ee6b7-282a-4d50-8a76-03806ea8fcb4">

默认情况下是仅显示 GBK 字集中的字。（如果你用的是一个较早版本可以更新一下。）

<img width="458" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/5fec3f72-d62c-4420-a651-c68a95fa3262">

辅助码是只与单字结合的，参见[FAQ 1](https://github.com/ksqsf/rime-moran/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C#%E4%B8%80%E5%95%8F%E9%AD%94%E6%94%B9%E4%B9%8B%E8%99%95%E4%BD%95%E5%9C%A8)，这是因为「词组」的概念很不明确。

如果需要补充输入前一字的辅助码，可以使用 Tab, Shift-Tab 等快捷键，也可以使用 Shift+<字母> 在上一个音节末尾增加输入（Shift+Backspace 删除上一个音节的末尾字符）。如 lmjxJ=链接, lmjxZ=连接。

**Comment by liangkaichun** [comment]
1. 这个配置选项再魔然里有，在魔然整句中没有。切换到魔然，选择了GBK：
<img width="320" alt="infoflow 2023-09-11 11-53-42" src="https://github.com/ksqsf/rime-moran/assets/3862788/8cb8786a-7e5a-4950-8c72-0fbc2ac71483">
候选项中依然有这些超集字存在，这个能隐藏或者直接去掉吗？超集字使用得场景太少了。
<img width="240" alt="infoflow 2023-09-11 11-54-30" src="https://github.com/ksqsf/rime-moran/assets/3862788/371ff61a-8780-4de6-9d16-090adc346f87">

2. 用tab等快捷键虽然可以切换辅助码辅助的音节，但在手机上就没有办法了。我理解这个情况，本质上就是支持
“词组中辅助码匹配词中首字”或者“词组中辅助码匹配词中任意字”，这个有可能实现吗？

**Comment by ksqsf** [comment]
感谢反馈，已修复 sentence 模式无 charset_filter 的问题。

不过我还不清楚为什么你那边不行，我这里鼠须管是可以的。（手机上的仓输入法目前还不支持 charset_filter，因为没有打包 librime-charcode 插件，参见 https://github.com/imfuxiao/LibrimeKit/issues/3 。）

<img width="388" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/771f5dec-efb7-4e97-9f0a-760f9d43e332">

要手动删除这些字的话，从 `moran.chars.dict.yaml` 里直接把带「auto」的条目全部删掉就可以了，这些字都是 GBK 集外的字。

词辅用 Rime 自带的功能无法实现，要写 Lua 脚本手动定义过滤过程。不过按我的理解，原理上的确是可行的，只能说「就差一个程序员了」。与此同时，也可以考虑使用落格、手心、小鹭音形、[henices/rime](https://github.com/henices/rime/) 等输入法或方案，他们都支持词辅。

**Comment by liangkaichun** [comment]
更新了最新的sentence [scheme文件，选项有了，但选择gbk后，对集外字的过滤还是没有生效，怀疑是我的鼠须管版本问题，我用了一个鼠须管的修改版本（(https://github.com/LEOYoon-Tsaw/squirrel)），我卸载了安装原版再试试。]

**Comment by liangkaichun** [comment]
重新安装了原版的鼠须管，对集外字的过滤生效了，看来是修改版的问题，我去那边提个bug，哈哈

**Comment by ksqsf** [comment]
假设该问题已解决，故关闭。
