### ISSUE TITLE
请问大佬如何把字或者词设置为首选（闪电）

### ISSUE THREAD

**Issue by FengAiLing2016** [ksqsf/rime-moran#15]
如题，谢谢大佬

**Comment by ksqsf** [comment]
固定简码码表在 moran_fixed.dict.yaml 中，可根据自己的需求进行修改定制，重新部署即可生效。

目前默认情况下不会开启词的固定，而仅固定 3 码以下的字词（逻辑在 lua/moran_express_translator.lua 中）。你可以打开「固词」模式，在输入 4 码时，会输出固定的 2 字词（在 Ctrl-` 的选单中可以开关；参阅 moran.defaults.yaml 以永久开启或关闭）。

此外，也可以修改 moran_custom.txt （自定义短语），这个和其他输入法的自定义短语功能一样，总是出现在首选，并且不受上述逻辑的限制。

**Comment by FengAiLing2016** [comment]
谢谢大佬的解答，用了个把星期，感觉还是很不错
