### ISSUE TITLE
请问大佬此方案不能用于同文输入法吗

### ISSUE THREAD

**Issue by FengAiLing2016** [ksqsf/rime-moran#17]
把魔然方案复制进去，也可以在同文的方案选择里查看，但是一旦选好点击确定部署，再返回同文一样还是旧的方案

**Comment by ksqsf** [comment]
根据一些用户的反馈，同文上使用需要手动安装 [rime-prelude](https://github.com/rime/rime-prelude) 数据。

（这个数据在其他 Rime 发行版上是自带的，但是同文没自带）

**Comment by FengAiLing2016** [comment]
现在部署成功了，但是就是打不了中文。

**Comment by ksqsf** [comment]
不客气~
