### ISSUE TITLE
macOS 14 鼠鬚管因 charset_filter 崩潰

### ISSUE THREAD

**Issue by ksqsf** [ksqsf/rime-moran#18]
已知在 macOS 14 上 charset_filter 會導致鼠鬚管在輸入某些符號時崩潰。該 issue 將在該問題得到任一方修復前保持開啓。

目前的臨時解決辦法是將默認的字集設置爲 UTF-8 （修改爲 `reset: 0`）從而避免字集過濾：

- [moran.schema.yaml#L31](https://github.com/ksqsf/rime-moran/blob/main/moran.schema.yaml#L31)
- [moran_sentence.schema.yaml#L27](https://github.com/ksqsf/rime-moran/blob/main/moran_sentence.schema.yaml#L27)

也可以考慮暫不升級到 macOS 14。

**Comment by FengAiLing2016** [comment]
暂时没遇见过

**Comment by liangkaichun** [comment]
我遇到这个问题了，我现在没有办法输入“……”，shift+6，只能输入^，若删除回去重新输入，鼠须管就崩溃了

**Comment by ksqsf** [comment]
苹果的某次系统升级修复了该问题。最新版本已经可以正常使用 charset_filter 了。
