### ISSUE TITLE
中文状态下，输入大写字母，当前是直接上屏，小写字母是回车上屏，这个该如何改成都是回车上屏？

### ISSUE THREAD

**Issue by liangkaichun** [ksqsf/rime-moran#19]
中文状态下，输入大写字母，当前是直接上屏，小写字母是回车上屏，这个该如何改成都是回车上屏？

**Comment by ksqsf** [comment]
<img width="133" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/599e300c-2f08-40be-9b19-07d2a62c835e">

未能复现，输入大写字母也是进入输入逻辑，按回车或空格上屏。

**Comment by liangkaichun** [comment]
![235f7cd4fc3f6fc22fdaae52d](https://github.com/ksqsf/rime-moran/assets/3862788/005da65a-3aaa-4a67-a132-aa6cf495451f)
MacOS 鼠须管，我录了个屏。

**Comment by ksqsf** [comment]
明白你的意思，不过我这里测试就是你想要的预期行为，所以暂时不明白是哪里的问题。 🤔

**Comment by liangkaichun** [comment]
好的，谢谢！那这个问题就先这样吧。

**Comment by FengAiLing2016** [comment]
`recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
      # uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"`
可以试一下把 uppercase 注释掉

**Comment by liangkaichun** [comment]
谢谢！搞定！
