### ISSUE TITLE
请问大佬有没有计划为安卓用户做个主题

### ISSUE THREAD

**Issue by FengAiLing2016** [ksqsf/rime-moran#20]
用了几个主题，都没有找到个很适合的，大佬有没有考虑呢？

**Comment by ksqsf** [comment]
我最近没用 Android 设备，所以暂时没有计划。如果你发现有比较合适的，可以推荐或者直接PR给我~

**Comment by FengAiLing2016** [comment]
研究了一下配置文件改了同文风的主题，现在试用中

**Comment by FengAiLing2016** [comment]
现在主要做助记码，再加上微小的改动
https://www.helloimg.com/image/oWw3lD
