### ISSUE TITLE
关于emoji滤镜的建议

### ISSUE THREAD

**Issue by shitlime** [ksqsf/rime-moran#22]
**建议使用更全面和更完善的emoji滤镜👇🏻️：**

[项目地址](https://github.com/rtransformation/rime-opencc_emoji_symbols)

**为何比原来的emoji强大？**

1. 其中有一些emoji之外的内容，如：（三字经、百家姓等）

https://github.com/rtransformation/rime-opencc_emoji_symbols/blob/245f7a371866eda8c244fff9fd420b529e5f5055/es.txt#L1914-L1923

2. 对于一些计量单位，其中有对应的符号

https://github.com/rtransformation/rime-opencc_emoji_symbols/blame/245f7a371866eda8c244fff9fd420b529e5f5055/es.txt#L1887-L1897

以上两点都是原本的emoji滤镜没有的特性。其不仅是emoji滤镜，还具有符号滤镜的功能。

此外，个人感觉这个emoji滤镜更全面，如：（笑包含的emoji比原本的更多）

https://github.com/rtransformation/rime-opencc_emoji_symbols/blob/245f7a371866eda8c244fff9fd420b529e5f5055/es.txt#L131

但是这个emoji滤镜是简体中文的，可能要换成繁体才能在魔然中使用。

**Comment by ksqsf** [comment]
感谢建议，看起来不错，稍后我整合一下
