### ISSUE TITLE
请问如何用moran.custom.yaml取消中英混输、虎码反查、仓颉反查，谢谢

### ISSUE THREAD

**Issue by davidlauhn** [ksqsf/rime-moran#23]
用自然码有15年了，自从自然码不再更新，一直用手心替代，RIME也折腾过，限于能力有限，也只能用用zrm2000.schema.yaml，但是存在很多不习惯的地方，作者的魔然是我用过的最接近原版自然码使用习惯的

有一个不习惯的地方就是，不太习惯中英混输，也不了解虎码和仓颉，只需要用到通配符反查、笔画反查和两分反查，请问如何将中英文混输、虎码反查、仓颉反查给取消掉？可以使用moran.custom.yaml吗？应该如何修改呢？不想动moran.schema.yaml，担心更新的时候忘记被覆盖掉。

另外，有没有可能如打 「需」的时候可以打  xv ，而不非得打 xu？ 谢谢。「我也不知道我是怎么养成了这么个坏习惯」

**Comment by ksqsf** [comment]
很遗憾，你提到的需求只能通过修改 moran.schema.yaml 实现，或者只有这样修改最简单的。moran.schema.yaml 文件本身近期不会做太大改动了，而且修改量并不大，所以建议还是通过这个方式实现。

1. 取消中英文混输，删掉「- table_translator@english             # 英語混輸」 这一行
2. 取消虎码反查，删掉「- reverse_lookup_translator@reverse_tiger」这一行
3. 取消仓颉反查，删掉「- reverse_lookup_translator@reverse_cangjie5」这一行
4. 使用 xv 编码需要在 `algebra` 添加对应的编码映射规则，可参考 [wiki 中的说明](https://github.com/ksqsf/rime-moran/wiki/%E5%AE%9A%E8%A3%BD%E6%80%9D%E8%B7%AF#%E6%81%A2%E5%BE%A9%E8%80%81%E8%87%AA%E7%84%B6%E7%A2%BC%E7%9A%84-jv-qv-xv-%E6%89%93%E6%B3%95)

上述修改在重新部署后生效。

**Comment by davidlauhn** [comment]
哇，回复真的好快哦

非常感谢

还有一个问题，如何删除误上屏的自造词？谢谢😄️

**Comment by ksqsf** [comment]
使用 Rime 本身的删词键, 迻动到要删除的候选词上, 按 `Ctrl+Delete` （Windows、Linux）或 `Shift+Fn+Delete`（macOS）删除

**Comment by davidlauhn** [comment]
试了，可能还是因为不是很熟悉rime，估计已经删除了，但是打同样错误的编码还是出现再候选框，误以为没有删除呢，谢谢
