### ISSUE TITLE
关于辅助码的繁简问题

### ISSUE THREAD

**Issue by shitlime** [ksqsf/rime-moran#24]
使用opencc转换来支持繁简输入有利有弊，比如繁体语境的一些词在简体中不适合（如简体：内存；繁体：記憶體），但在音形输入方案中有新的问题：

**词语的形码是否只取繁体？**

以下是两个字以及它组词的例子：
+ 体 體
  - 主体    vu tig  *（应为 vu tir）*
  - 客体    ke tig  *（应为 ke tir）*
  - *等以“体”结尾的词*
+ 义 義
  - 正义    vg yiy  *（应为 vg yid）*
  - *等以 “义”结尾的词*

如果词库的词语形码只取繁体，希望有提供对应的简体形码词库

**Comment by ksqsf** [comment]
是的，目前的词库只有繁体的辅助码，这个问题如何妥善解决我也还在思考。

当前没有包含简体词库的主要顾虑是：

1. 词库文件太大了，比如tencent有41M。
2. 另外简体的简码也需要另行设计。（已有一些志愿者在制作简体简码码表，所以这一点已经不是问题了。）
3. 简繁需要不同的schema，显得有点杂乱。

（一开始的打算是：用户如果有需要可以自行使用 tools 目录下的 Python 脚本产生自己想要的词库，不过看起来门槛还是太高了，从来没人用过，Orz）

除了“制作单独词库”的方法外，我最近考虑过的另一个思路是引入 [rime-lua-aux-code](https://github.com/HowcanoeWang/rime-lua-aux-code/) （即放弃辅助码混输，只使用辅助码筛选）。不过 rime-lua-aux-code 现在还不支持直接辅助码，我自己使用起来觉得有点别扭，还需要进一步的开发。

如果有更好的想法，欢迎交流~

**Comment by shitlime** [comment]
> 是的，目前的词库只有繁体的辅助码，这个问题如何妥善解决我也还在思考。
> 
> 当前没有包含简体词库的主要顾虑是：
> 
>     1. 词库文件太大了，比如tencent有41M。
> 
>     2. 简体的简码也需要另行设计。（已有一些志愿者在制作简体简码码表，所以这一点已经不是问题了。）
> 
>     3. 简繁需要不同的schema，显得有点杂乱。
> 
> 
> （一开始的打算是：用户如果有需要可以自行使用 tools 目录下的 Python 脚本产生自己想要的词库，不过看起来门槛还是太高了，从来没人用过，Orz）
> 
> 除了“制作单独词库”的方法外，我最近考虑过的另一个思路是引入一个基于 [rime-lua-aux-code](https://github.com/HowcanoeWang/rime-lua-aux-code/) 的新方案（辅助码只能筛选而不能混输；因为是在 simplifier 之后生效的，所以可以同时支持简繁体）。不过 rime-lua-aux-code 现在还不支持直接辅助码，我自己使用起来觉得有点别扭，还需要进一步的开发。
> 
> 如果有更好的想法，欢迎交流~

看了[rime-lua-aux-code](https://github.com/HowcanoeWang/rime-lua-aux-code/)，这是一个很好的辅助码思路。

它不仅可以完美解决辅助码繁简问题，还能大大轻量化词库。

关键点在于解决辅助码问题，它使用 `lua_filter` 在opencc简体滤镜作用之后再使用辅助码筛选，这个想法非常棒；但是缺点在于不能直接输入辅助码，需要使用 `;` 来区分输入的是辅助码。 *或许是 `filter` 的局限？*

其实，我觉得可以换个思路。

使用 `lua_translator` 解决这个问题，在原有的 [moran_express_translator.lua](https://github.com/ksqsf/rime-moran/blob/main/lua/moran_express_translator.lua) 基础上进行修改，基本的思路是：

1. 魔然原本的单字规则不变（单字有Y、YY、YYX、YYXX（低优先度）、YYXXo（高优先度））
2. 词根据字引入额外的辅助码，而词库中不再写入辅助码，关于这要解决的问题如下：
    + **Q1：** 繁简辅助码的问题如何解决？由于 `lua_translator` 在 `filter` 组件（即opencc简体滤镜）之前，如何解决繁简辅助码问题？
    - **A1:** `rime-lua` 应该可以使用 `env.engine.context:get_option` 接口获取当前 `simplification` 的状态，根据这个状态使用对应的繁/简体辅助码
    + **Q2：** `lua_translator` 的行为变化？
    - **A2:** `lua_translator` 保持原本4码优先出词；辅助码不参与造词，只起到在translator的级别对词进行筛选
3. 目前只想到这些，抛砖引玉

*希望这个issue能提供讨论空间，先别关(＞﹏＜)*

**Comment by shitlime** [comment]
现有的简体码表是不是没有小闪电的功能

**Comment by ksqsf** [comment]
> 现有的简体码表是不是没有小闪电的功能

我测试了一下是ok的。没有闪电可能是因为 moran_fixed_simp 词库没有编译导致 fixed translator 没有输出？可否确认下 build 目录下是否有 moran_fixed_simp.table.bin 文件？

**Comment by shuen2023** [comment]
简化字体库是不是有问题。为什么"涂"是tut？而不是tud

**Comment by ksqsf** [comment]
@shuen2023 你用的应该不是简体字码表，而是繁体字「塗」转换成简体字的结果。

**Comment by shuen2023** [comment]
> @shuen2023 你用的应该不是简体字码表，而是繁体字「塗」转换成简体字的结果。

那我该怎么使用简体码表辅码？

**Comment by ksqsf** [comment]
> > @shuen2023 你用的应该不是简体字码表，而是繁体字「塗」转换成简体字的结果。
> 
> 那我该怎么使用简体码表辅码？我用的小企鹅安卓版。

参考 moran.defaults.yaml 替换码表

**Comment by ksqsf** [comment]
> 使用简体码表后： 义 yii
> 
> 这是否为错码？

简体码表不是我制作的，不过我倾向于不是，这里的 i 应该是对应于 乂

**Comment by shuen2023** [comment]
> > @shuen2023 你用的应该不是简体字码表，而是繁体字「塗」转换成简体字的结果。
> 
> 那我该怎么使用简体码表辅码？我用的小企鹅安卓版。

我觉得我暂时还是不换了吧。担心弄乱了。另外还有一点。我看到那个义字对应的yii，在自然码辅码官方我看只有w上对应的让我理解。但它对应i我不理解。首先，乂它本身就拼yi。i上面没有这个乂字旁不说它也没有一个叫义的偏旁。

**Comment by ksqsf** [comment]
> > > @shuen2023 你用的应该不是简体字码表，而是繁体字「塗」转换成简体字的结果。
> > 
> > 
> > 那我该怎么使用简体码表辅码？我用的小企鹅安卓版。
> 
> 我觉得我暂时还是不换了吧。担心弄乱了。另外还有一点。我看到那个义字对应的yii，在自然码辅码官方我看只有w上对应的让我理解。但它对应i我不理解。首先，乂它本身就拼yi。i上面没有这个乂字旁不说它也没有一个叫义的偏旁。

这个 i 我的理解是对应于「叉」，比如「希」也是 xii。目前是依据现有的公开码表制作的，和自然码官方的说明书在一些细节上略有不符，这个「乂」就是一例。（说实话我也不清楚这个码表最初的来源是哪里。）这些问题可能需要以后收集一下统一考虑了。

**Comment by shuen2023** [comment]
> > > > @shuen2023 你用的应该不是简体字码表，而是繁体字「塗」转换成简体字的结果。
> > > 
> > > 
> > > 那我该怎么使用简体码表辅码？我用的小企鹅安卓版。
> > 
> > 
> > 我觉得我暂时还是不换了吧。担心弄乱了。另外还有一点。我看到那个义字对应的yii，在自然码辅码官方我看只有w上对应的让我理解。但它对应i我不理解。首先，乂它本身就拼yi。i上面没有这个乂字旁不说它也没有一个叫义的偏旁。
> 
> 这个 i 我的理解是对应于「叉」，比如「希」也是 xii。目前是依据现有的公开码表制作的，和自然码官方的说明书在一些细节上略有不符，这个「乂」就是一例，按官方的字根表大概应该是 x。（说实话我也不清楚这个码表最初的来源是哪里。）这些问题可能需要以后收集一下统一另作考虑了。

抱歉，我又去看了下。有这个乂字旁在y键上。但是码表不应该是i。应该是y或者d吧才合理。大佬以后有时间给整理下码表吧。最起码容易记的。像希我觉得也可以是xiyb/xiyj，毕竟按照官方自然码辅码码表y键上就那个希字吧。但我不懂为啥我打出来的那个可以是yiy。当然我繁体字基本都不大认识。

**Comment by shuen2023** [comment]
> > > > @shuen2023 你用的应该不是简体字码表，而是繁体字「塗」转换成简体字的结果。
> > > 
> > > 
> > > 那我该怎么使用简体码表辅码？我用的小企鹅安卓版。
> > 
> > 
> > 我觉得我暂时还是不换了吧。担心弄乱了。另外还有一点。我看到那个义字对应的yii，在自然码辅码官方我看只有w上对应的让我理解。但它对应i我不理解。首先，乂它本身就拼yi。i上面没有这个乂字旁不说它也没有一个叫义的偏旁。
> 
> 这个 i 我的理解是对应于「叉」，比如「希」也是 xii。目前是依据现有的公开码表制作的，和自然码官方的说明书在一些细节上略有不符，这个「乂」就是一例，按官方的字根表大概应该是 x。（说实话我也不清楚这个码表最初的来源是哪里。）这些问题可能需要以后收集一下统一另作考虑了。

我顿时很赞同你的理解😂如果按x理解似乎也很合适。

**Comment by shuen2023** [comment]
> > > @shuen2023你用的应该不是简体字码表，而是繁体字「涂」转换成简体字的结果。
> > 
> > 
> > 那我该用简体码表辅码吗？我用小企鹅安卓版。
> 
> 参考 moran.defaults.yaml 替换码表

谢谢，修改完成了，很棒😌。就是我没有找到你在文档里面提到的moran.custom.yaml文件，没能做备份。

**Comment by davidlauhn** [comment]
在 `moran.custom.yaml` 里添加

```
patch:
    "fixed/dictionary": moran_fixed_simp
```

然后在 `moran_fixed.custom.yaml` 里添加

```
patch:
  "translator/dictionary": &dict moran_fixed_simp
```

还是不能用 `vutir` 打出 「主体」，而是 「墸传」，请问我是哪里理解错了呢？

**Comment by ksqsf** [comment]
> 在 `moran.custom.yaml` 里添加
> 
> ```
> patch:
>   "moran/enable_word_filter": true
>   "fixed/dictionary": moran_fixed_simp
> ```
> 
> 然后在 `moran_fixed.custom.yaml` 里添加
> 
> ```
> patch:
>   "translator/dictionary": &dict moran_fixed_simp
> ```
> 
> 还是不能用 `vutir` 打出 「主体」，而是 「墸传」，请问我是哪里理解错了呢？

词库还是繁体的，词库里只有「主體」而没有「主体」。上屏一次「主体」造词之后就可以了。这个问题目前我还没想到比较好的解决办法。

**Comment by davidlauhn** [comment]
> > 在 `moran.custom.yaml` 里添加
> > ```
> > patch:
> >   "moran/enable_word_filter": true
> >   "fixed/dictionary": moran_fixed_simp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后在 `moran_fixed.custom.yaml` 里添加
> > ```
> > patch:
> >   "translator/dictionary": &dict moran_fixed_simp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还是不能用 `vutir` 打出 「主体」，而是 「墸传」，请问我是哪里理解错了呢？
> 
> 词库还是繁体的，词库里只有「主體」而没有「主体」。上屏一次「主体」造词之后就可以了。这个问题目前我还没想到比较好的解决办法。

我也想到了，可惜上面提到的tools里的脚本不会用，只能耐心等待大佬你解决了😄️

**Comment by shitlime** [comment]
> 想了个凑合的办法，通过软件自动将繁体词库转换为简体词库，从而避免手动维护两个方案。这个办法对 Git 用户不是很友好，不过目前方案趋于稳定，也不需要经常升级，应该不会有太大问题。
> 
> 现在每次push都会自动产生对应的简体版本了。例如刚刚的 CI build： https://github.com/ksqsf/rime-moran/actions/runs/7047605834
> <img alt="image" width="542" src="https://private-user-images.githubusercontent.com/23358293/286957592-c6b71828-321d-4820-8560-5b4d0f30e975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTU5NDMsIm5iZiI6MTcwMTM1NTY0MywicGF0aCI6Ii8yMzM1ODI5My8yODY5NTc1OTItYzZiNzE4MjgtMzIxZC00ODIwLTg1NjAtNWI0ZDBmMzBlOTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE0NDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NGE0MWE2NDIyNzg1MDU3MDUwM2E5YmJmNjNhNDMxZjk4OTVlN2Y0NmYwZjViNDNmNzAxNDU4NGJmMjNmM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NpgJ4eV6nRL6gPB_5zjhNVl1EDTCm1cpi7YGreOw1y8">
> 
> 点击「MoranSimplified」即可下载。

1. 没必要嵌套压缩吧，github artifacts是默认压缩的，没必要套一层 `7z`
2. 建议只打包词库文件，这样方便部分修改配置文件的用户 ~~（因为现在的缺点是配置文件打补丁难度较大）~~

**Comment by ksqsf** [comment]
> > 想了个凑合的办法，通过软件自动将繁体词库转换为简体词库，从而避免手动维护两个方案。这个办法对 Git 用户不是很友好，不过目前方案趋于稳定，也不需要经常升级，应该不会有太大问题。
> > 现在每次push都会自动产生对应的简体版本了。例如刚刚的 CI build： https://github.com/ksqsf/rime-moran/actions/runs/7047605834
> > <img alt="image" width="542" src="https://private-user-images.githubusercontent.com/23358293/286957592-c6b71828-321d-4820-8560-5b4d0f30e975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTU5NDMsIm5iZiI6MTcwMTM1NTY0MywicGF0aCI6Ii8yMzM1ODI5My8yODY5NTc1OTItYzZiNzE4MjgtMzIxZC00ODIwLTg1NjAtNWI0ZDBmMzBlOTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE0NDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NGE0MWE2NDIyNzg1MDU3MDUwM2E5YmJmNjNhNDMxZjk4OTVlN2Y0NmYwZjViNDNmNzAxNDU4NGJmMjNmM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NpgJ4eV6nRL6gPB_5zjhNVl1EDTCm1cpi7YGreOw1y8">
> > 点击「MoranSimplified」即可下载。
> 
> 1. 没必要嵌套压缩吧，github artifacts是默认压缩的，没必要套一层 `7z`

Point taken!

> 2. 建议只打包词库文件，这样方便部分修改配置文件的用户 ~（因为现在的缺点是配置文件打补丁难度较大）~

已增加仅词库artifact

> 3. 简体辅助码是否没有生效？ `moran.essay.dict.yaml` 中的81888行：
> 
> ```
> 意义	yi;lx yi;yw	13756
> ```
> 
> 还是繁体的辅助码 `義yiyw` 其他 `义` 字似乎正常，建议严查程序bug

已修复：https://github.com/ksqsf/rime-moran/actions/runs/7049360638

一个意想不到的地方出的问题 = =

**Comment by davidlauhn** [comment]
> > > 想了个凑合的办法，通过软件自动将繁体词库转换为简体词库，从而避免手动维护两个方案。这个办法对 Git 用户不是很友好，不过目前方案趋于稳定，也不需要经常升级，应该不会有太大问题。
> > > 现在每次push都会自动产生对应的简体版本了。例如刚刚的 CI build： https://github.com/ksqsf/rime-moran/actions/runs/7047605834
> > > <img alt="image" width="542" src="https://private-user-images.githubusercontent.com/23358293/286957592-c6b71828-321d-4820-8560-5b4d0f30e975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTU5NDMsIm5iZiI6MTcwMTM1NTY0MywicGF0aCI6Ii8yMzM1ODI5My8yODY5NTc1OTItYzZiNzE4MjgtMzIxZC00ODIwLTg1NjAtNWI0ZDBmMzBlOTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE0NDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NGE0MWE2NDIyNzg1MDU3MDUwM2E5YmJmNjNhNDMxZjk4OTVlN2Y0NmYwZjViNDNmNzAxNDU4NGJmMjNmM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NpgJ4eV6nRL6gPB_5zjhNVl1EDTCm1cpi7YGreOw1y8">
> > > 点击「MoranSimplified」即可下载。
> > 
> > 
> > 
> > 1. 没必要嵌套压缩吧，github artifacts是默认压缩的，没必要套一层 `7z`
> 
> Point taken!
> 
> > 2. 建议只打包词库文件，这样方便部分修改配置文件的用户 ~（因为现在的缺点是配置文件打补丁难度较大）~
> 
> 已增加仅词库artifact
> 
> > 3. 简体辅助码是否没有生效？ `moran.essay.dict.yaml` 中的81888行：
> > 
> > ```
> > 意义	yi;lx yi;yw	13756
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还是繁体的辅助码 `義yiyw` 其他 `义` 字似乎正常，建议严查程序bug
> 
> 已修复：https://github.com/ksqsf/rime-moran/actions/runs/7049459210
> 
> 一个意想不到的地方出的问题 = =

果然是大神👍🏻👍🏻👍🏻👍🏻👍🏻

用起来顺手多了，感觉都快可以盲打了

**Comment by shuen2023** [comment]
魔然的"在"字打辅码出来似乎有点问题。如果选择魔然不选魔然整句。zlta是不起作用得。zlut又会多出个z的标示。但我在那个easy词库看到在字是zl;ta
![Screenshot_20240306_090155_com android chrome](https://github.com/ksqsf/rime-moran/assets/133501179/3db2f542-354b-4c8e-8a7d-0ed0ff424ffa)

**Comment by ksqsf** [comment]
> 魔然的"在"字打辅码出来似乎有点问题。如果选择魔然不选魔然整句。zlta是不起作用得。zlut又会多出个z的标示。但我在那个easy词库看到在字是zl;ta 

感谢报告，这里有多个问题，所以我一一回答一下。

1. 字表（chars）中「在」存在 zlta 和 zlut 两种编码。其中 zlta 可以被理解成两个双拼，因此需要使用补码，实际需要输入 zltao（参见[教程](https://github.com/ksqsf/rime-moran/wiki/%E6%95%99%E7%A8%8B#%E5%85%B6%E4%B8%89%E6%9B%B0%E5%96%AE%E5%AD%97%E8%BC%B8%E5%85%A5%E6%96%B9%E5%BC%8F)）。
2. 提示 `z` 是因为「在」是一级简码字，`z` 表示单用 z 即可输入该字。简码字默认会「出简让全」（输入全码时优先级降低）。输入 zltao 时，「在」会被放在第二页（出简让全是可选功能，默认开启，可手动在 moran.schema.yaml 中关闭）。因此打这个字的时候不需要输入 zltao 或 zluto，直接 z 空格即可。
3. essay 词库中看到 zl;ta 而没有 zl;ut 是因为每个词默认只使用了一个编码（出于在手机上部署的考虑，如果每个字都包含了所有编码，会消耗大量内存）。目前，chars 表中 **每个字的第一个编码** 会被用于词语编码。有的时候顺序因为种种原因是不正确的，所以时不时还会作一些调整，保证词库和简码码表是对应的。参见[该wiki页面](https://github.com/ksqsf/rime-moran/wiki/%E5%8F%83%E8%88%87%E8%B2%A2%E7%8D%BB#%E6%95%B4%E5%8F%A5%E8%A9%9E%E5%BA%AB%E8%BC%94%E7%A2%BC%E5%95%8F%E9%A1%8C)。

**Comment by shuen2023** [comment]
> > 魔然的“在”字打辅码出来似乎有点问题。如果选择魔然不选魔然整句。zlta是无效得。zlut也多出了个z的标记。但我在那个easy词库看到了字是zl;ta
> 
> 感谢报告，这里有很多问题，所以我一一回答一下。
> 
> 1. 字表（chars）中「在」存在 zlta 和 zlut 两种编码。其中 zlta 可以被理解成两个双拼，因此需要使用补码，实际需要输入 zltao（参见[教程](https://github.com/ksqsf/rime-moran/wiki/%E6%95%99%E7%A8%8B#%E5%85%B6%E4%B8%89%E6%9B%B0%E5%96%AE%E5%AD%97%E8%BC%B8%E5%85%A5%E6%96%B9%E5%BC%8F)）。
> 2. 提示`z`是因为「在」是一级简码字，`z`表示单用 z 即可输入该字。简码字默认会「出简让全」（输入全码时优先级降低）。输入 zltao 时，「在」会被放在第二页（出简全是可选功能，默认开启，可手动在 moran.schema.yaml 中关闭）。因此打这个字的时候不需要输入 zltao 或 zluto，直接 z 空格即可。
> 3. 论文词库中看到zl;ta而没有zl;ut是因为每个词默认只使用了一个编码（由于在手机上部署的，如果每个字都包含了所有编码，会消耗大量内存）目前， chars表中**每个字的第一个编码**会被用于词汇编码。有的时候顺序因为上述一些原因是不正确的，所以时不时会做调整，保证词库和简码表是对应的。除了[该wiki页面](https://github.com/ksqsf/rime-moran/wiki/%E5%8F%83%E8%88%87%E8%B2%A2%E7%8D%BB#%E6%95%B4%E5%8F%A5%E8%A9%9E%E5%BA%AB%E8%BC%94%E7%A2%BC%E5%95%8F%E9%A1%8C)。

噢。谢谢！

**Comment by ksqsf** [comment]
自从添加了简体版本之后，除了几个小问题（无法直接用git更新、无法用plum安装）和简码码表维护的额外成本以外感觉还好。因此我目前认为该议题已解决，如需进一步讨论可继续回复或reopen。
