### ISSUE TITLE
安卓版部署时报错

### ISSUE THREAD

**Issue by shuen2023** [ksqsf/rime-moran#26]
你好！  
我的手机是华为的。我安装好了同文输入法Fdroid最新版。并且我拉取了仓库，它的上一层文件夹是安装同文输入法默认生成的。我也在同文里选择了这个文件夹(里面只包含了这个github仓库的所有东西)，可当我部署的时候出现报错。       

![Screenshot_20231111_221501_com termux](https://github.com/ksqsf/rime-moran/assets/133501179/29b00033-92a1-4b9b-96c4-04455bc3723d)
![Screenshot_20231111_215653_com osfans trime](https://github.com/ksqsf/rime-moran/assets/133501179/59d4af87-29e3-4c11-9006-59cfee7b437e)
![Screenshot_20231111_215648_com osfans trime](https://github.com/ksqsf/rime-moran/assets/133501179/034d0456-0642-4418-ade4-d509b4b6b3b2)
![Screenshot_20231111_215658_com osfans trime](https://github.com/ksqsf/rime-moran/assets/133501179/508b5306-446f-4a0b-b3db-87d12156c731)

同文日志文件.  
[com.osfans.trime-2023-11-11T13_52_41Z.txt](https://github.com/ksqsf/rime-moran/files/13325732/com.osfans.trime-2023-11-11T13_52_41Z.txt)    

不过，我倒是可以使用。就是一开始部署完成后不能调出同文我关机重启后便可以使用，就是不知道会不会影响到其它的什么。暂时没有发现。

**Comment by shuen2023** [comment]
在我选择其它方案部署就报错。

**Comment by ksqsf** [comment]
这些都是不影响使用的警告。

`charset_filter` 不存在的时候字集过滤功能不生效，但是正常打字是没问题的。这个组件计划以后替换成 Lua 实现。

（invalid metadata 我在本地部署的时候也注意到过，不过因为警告信息没指出到底哪里 invalid，所以我也不知道哪里下手改……）

**Comment by ksqsf** [comment]
OK，找到了 invalid metadata 是自定义短语文件的问题，master 已修复。

> 在我选择其它方案部署就报错。

这个问题有没有更多的情报？

**Comment by shuen2023** [comment]
> 这些都不影响使用的警告。
> 
> `charset_filter`不存在的时候字集过滤功能不生效，但是正常打字是没问题的。这个组件计划以后替换成Lua实现。
> 
> （无效的元数据我在本地部署的时候也注意到过，不过因为警告信息没有发现到底哪里无效而且没有什么影响，所以我也不知道哪里下手改……）

😉️谢谢

**Comment by shuen2023** [comment]
> OK，找到了 invalid metadata 是自定义短语文件的问题，master 已修复。
> 
> > 在我选择其它方案部署就报错。
> 
> 这个问题有没有更多的情报？

俺好像找不到更多的情报了 。。

**Comment by ksqsf** [comment]
对了，根据之前用户的反馈，在同文上还需要添加 2 个 rime-prelude 中的文件：

> 複製粘貼 [rime-prelude](https://github.com/rime/rime-prelude) 中的 key_bindings.yaml 和 punctuation.yaml，否則無法正常部署

**Comment by shuen2023** [comment]
> 对了，根据之前用户的反馈，在同文上还需要添加 2 个 rime-prelude 中的文件：
> 
> > 複製粘貼 [rime-prelude](https://github.com/rime/rime-prelude) 中的 key_bindings.yaml 和 punctuation.yaml，否則無法正常部署

我把这两个文件放在了我克隆你的这个项目的文件夹下了。也就是我指定的用户文件夹。    
我刚才又git pull了下这个库。虽然选择方案部署不报错了，但是选择完后。输入法直接调不出来了，看不到键盘界面我只能重启手机。重启完后看到不熟成功同时看到同文报错日志。下面最新得报错日志。  
[com.osfans.trime-2023-11-11T14_47_40Z.txt](https://github.com/ksqsf/rime-moran/files/13325799/com.osfans.trime-2023-11-11T14_47_40Z.txt)

**Comment by ksqsf** [comment]
的确，我也复现了这个问题：设置好配置文件路径后，部署过程没有提示错误，但在提示部署完成之前同文界面就闪退，随后键盘本身也显示不出来了。重启系统后，键盘可以正常呼出，并输入。但重新部署会提示错误，找不到 `luna_pinyin`。手动从 default.yaml 中删除 `luna_pinyin` 后就没有任何问题了。

我目前的理解是因为同文没有内置 `luna_pinyin` 方案，导致 `default.yaml` 中对它的引用是无效的。你可以尝试去掉这一行再重新部署看看，应该不会有问题了。

**Comment by shuen2023** [comment]
> 的确，我也复现了这个问题：设置好配置文件路径后，部署过程没有提示错误，但在提示部署完成之前同文界面就闪退，随后键盘本身也显示不出来了。重启系统后，键盘可以正常呼出，并可以使用魔然输入文字。但重新部署会提示错误，找不到 `luna_pinyin`。手动从 default.yaml 中删除 `luna_pinyin` 后就没有任何问题了。
> 
> 我目前的理解是因为同文没有内置 `luna_pinyin` 方案，导致 `default.yaml` 中对它的引用是无效的。你可以尝试去掉这一行再重新部署看看，应该不会有问题了。

嗯，我之前回复的不对，切换还是会报错。那么我试了你得这个方法还是报错。  
![Screenshot_20231111_235146_com osfans trime](https://github.com/ksqsf/rime-moran/assets/133501179/85254c52-7a3a-4bfb-8205-d8aff11a8fe7)

**Comment by shuen2023** [comment]
> 的确，我也复现了这个问题：设置好配置文件路径后，部署过程没有提示错误，但在提示部署完成之前同文界面就闪退，随后键盘本身也显示不出来了。重启系统后，键盘可以正常呼出，并可以使用魔然输入文字。但重新部署会提示错误，找不到 `luna_pinyin`。手动从 default.yaml 中删除 `luna_pinyin` 后就没有任何问题了。
> 
> 我的理解是因为同文没有内置 `luna_pinyin` 方案，导致 `default.yaml` 中对它的引用是无效的。你可以尝试去掉这一行再重新部署看看，应该不会有问题了。

我是把default.yaml里面得一行luna_pinyin删掉了。

**Comment by ksqsf** [comment]
刚才给的错误日志里只有这些错误，我怀疑可能是共享文件夹设置到了同文没有权限读写的地方，但是看最开始的截图好像又是正常的…… 这个我也不清楚了🤔️

```
E/FileIOUtils( 6374): create file </rime/opencc/HKVariants.txt> failed.
E/FileIOUtils( 6374): create file </rime/opencc/HKVariantsRev.txt> failed.
E/FileIOUtils( 6374): create file </rime/opencc/HKVariantsRevPhrases.txt> failed.
E/FileIOUtils( 6374): create file </rime/opencc/JPShinjitaiCharacters.txt> failed.
E/FileIOUtils( 6374): create file </rime/opencc/JPShinjitaiPhrases.txt> failed.
E/FileIOUtils( 6374): create file </rime/opencc/JPVariants.txt> failed.
E/FileIOUtils( 6374): create file </rime/opencc/STCharacters.txt> failed.
...
```

**Comment by shuen2023** [comment]
> 刚才给的错误日志里只有这些错误，我怀疑可能是共享文件夹设置到了同文没有权限读写的位置，但是看最开始的截图好像又是正常的……这个我也狮子了🤔️
> 
> ```
> E/FileIOUtils( 6374): create file </rime/opencc/HKVariants.txt> failed.
> E/FileIOUtils( 6374): create file </rime/opencc/HKVariantsRev.txt> failed.
> E/FileIOUtils( 6374): create file </rime/opencc/HKVariantsRevPhrases.txt> failed.
> E/FileIOUtils( 6374): create file </rime/opencc/JPShinjitaiCharacters.txt> failed.
> E/FileIOUtils( 6374): create file </rime/opencc/JPShinjitaiPhrases.txt> failed.
> E/FileIOUtils( 6374): create file </rime/opencc/JPVariants.txt> failed.
> E/FileIOUtils( 6374): create file </rime/opencc/STCharacters.txt> failed.
> ...
> ```   

我倒是觉得有可能跟这个key_bindings.yaml有关吧？这个是空文件？  
我重新卸载装了几次。原本在rime文件下的用户文件夹我单独放在了别的地方，也就是说不在默认的rime文件夹下了。只要不是下图那种在键盘选择方案部署，而是到同文设置里面去部署，好像不报错了。  

![Screenshot_20231112_002426_com tencent mm](https://github.com/ksqsf/rime-moran/assets/133501179/44f615db-5243-45d3-8434-1e76972e9877)

**Comment by ksqsf** [comment]
配置里目前没有 `key_bindings.yaml` ，[rime-prelude 里的文件并不是空的](https://github.com/rime/rime-prelude/blob/master/key_bindings.yaml)，可能刚才你忘了粘贴进去？

不管怎么样，现在没问题了就好 😉

**Comment by shuen2023** [comment]
> 配置里目前没有 `key_bindings.yaml` ，[rime-prelude 里的文件并不是空的](https://github.com/rime/rime-prelude/blob/master/key_bindings.yaml)，可能刚才你忘了粘贴进去？
> 
> 不管怎么样，现在没问题了就好 😉

我现在完全打不开那个输入法了，打开直接报错退出。原因是我重新下载了那两个文件到用户文件夹下。我很确定俩文件里面都是有内容且应该是完整的。但这次我在重新部署直接错报到我根本没办法打开。算了我暂时不在手机上搞了。

**Comment by ksqsf** [comment]
Orz，那这个 issue 先留着，留待后续解决

**Comment by ksqsf** [comment]
BTW，我刚刚尝试了 Fcitx5-Android Rime 插件，也挺折腾的。。。不过我简短描述一下步骤：

1. 下载 fcitx5-android updater： https://github.com/fcitx5-android/fcitx5-android-updater （jenkins 页面上有一个 apk 链接）
2. 通过 updater 安装 f5a 和 rime 插件
3. 在 f5a 设置中的「插件」确认 rime 插件已经成功加载
4. 在 f5a 的「输入法」设置中，添加「中州韵」
5. 点击「中州韵」旁边的齿轮，再点击「用户数据目录」，确认用户目录的位置
6. 把配置拷贝到用户目录中
7. 切换点击🌐图标切换输入法到「中州韵」，自动部署，完成后应该可以使用

**Comment by FengAiLing2016** [comment]
> BTW，我刚刚尝试了 Fcitx5-Android Rime 插件，也挺折腾的。。。不过我简短描述一下步骤：
> 
> 1. 下载 fcitx5-android updater： https://github.com/fcitx5-android/fcitx5-android-updater （jenkins 页面上有一个 apk 链接）
> 2. 通过 updater 安装 f5a 和 rime 插件
> 3. 在 f5a 设置中的「插件」确认 rime 插件已经成功加载
> 4. 在 f5a 的「输入法」设置中，添加「中州韵」
> 5. 点击「中州韵」旁边的齿轮，再点击「用户数据目录」，确认用户目录的位置
> 6. 把配置拷贝到用户目录中
> 7. 切换点击🌐图标切换输入法到「中州韵」，自动部署，完成后应该可以使用

请问这是什么APP？同文的更新app吗

**Comment by shuen2023** [comment]
> BTW，我刚刚尝试了 Fcitx5-Android Rime 插件，也挺折腾的。。。不过我简短描述一下步骤：
> 
> 1. 下载 fcitx5-android updater： https://github.com/fcitx5-android/fcitx5-android-updater （jenkins 页面上有一个 apk 链接）
> 2. 通过 updater 安装 f5a 和 rime 插件
> 3. 在 f5a 设置中的「插件」确认 rime 插件已经成功加载
> 4. 在 f5a 的「输入法」设置中，添加「中州韵」
> 5. 点击「中州韵」旁边的齿轮，再点击「用户数据目录」，确认用户目录的位置
> 6. 把配置拷贝到用户目录中
> 7. 切换点击🌐图标切换输入法到「中州韵」，自动部署，完成后应该可以使用

这个方法看起来似乎能避开同文。我觉得很新颖但我失败了。我发现中州的文件在Android/data/fa5下面，作为华为手机用户我没权限移动文件进去   
![Screenshot_20231112_102311_org fcitx fcitx5 android](https://github.com/ksqsf/rime-moran/assets/133501179/6c58b2b8-251c-40a9-84fe-80e8f72821be)
![Screenshot_20231112_102008_com huawei android internal app](https://github.com/ksqsf/rime-moran/assets/133501179/d80a5f6f-7aee-4cc0-a6e8-0999bcd08c2a)       
这样看比较直观，即使我从华为文件夹进，能进但不能操作文件  。   
我理解的你的意思是复制rime-moran的文件到中州文件下rime文件里面。我觉得得把整个moran文件都移到到里面。只可惜我没权限  
![Screenshot_20231112_102658_com termux](https://github.com/ksqsf/rime-moran/assets/133501179/ca9f5155-0eb6-4823-8056-36de479ce754)

**Comment by shuen2023** [comment]
如果我没理解错fcitx5=f5a=小企鹅输入法。我真的才知道小企鹅这么牛逼！我以前用过甚至我都还没卸载它。但它没有我想要的辅助方案。我记得针对它对双拼和自然码的命名我还去给开发者提过异议，我认为它的命名不大容易理解。  
现在你给了方案，可又不能在上面用。唉，论稳定我觉得还是小企鹅稳定，比起同文。

**Comment by shuen2023** [comment]
> BTW，我刚刚尝试了 Fcitx5-Android Rime 插件，也挺折腾的。。。不过我简短描述一下步骤：
> 
> 1. 下载 fcitx5-android updater： https://github.com/fcitx5-android/fcitx5-android-updater （jenkins 页面上有一个 apk 链接）
> 2. 通过 updater 安装 f5a 和 rime 插件
> 3. 在 f5a 设置中的「插件」确认 rime 插件已经成功加载
> 4. 在 f5a 的「输入法」设置中，添加「中州韵」
> 5. 点击「中州韵」旁边的齿轮，再点击「用户数据目录」，确认用户目录的位置
> 6. 把配置拷贝到用户目录中
> 7. 切换点击🌐图标切换输入法到「中州韵」，自动部署，完成后应该可以使用

我在我的旧的华为mate20手机上实验成功了!😀  
我很开心简直太丝滑了!!    

![1699770716491](https://github.com/ksqsf/rime-moran/assets/133501179/60cfe0e8-3bc3-4a3f-bcf7-0fd05a2ac6cb)
![1699770732857](https://github.com/ksqsf/rime-moran/assets/133501179/33d12e66-01e8-419b-8d7c-7a2e75642e0a)     

我想可能是手机系统的原因，我没办法进入data目录的是华为鸿蒙4，也就是昨晚鼓捣一晚上的手机。而旧手机是鸿蒙3。    
这个小企鹅输入法太好用喇叭!你昨晚删掉的代码片段那个luna_pinyin要不要在添加回来，我担心会影响使用。昨晚一直有问题的是同文。而这个小企鹅它太丝滑了!怪不得星星涨的那么快😁

**Comment by ksqsf** [comment]
> > BTW，我刚刚尝试了 Fcitx5-Android Rime 插件，也挺折腾的。。。不过我简短描述一下步骤：
> > 
> > 1. 下载 fcitx5-android updater： https://github.com/fcitx5-android/fcitx5-android-updater （jenkins 页面上有一个 apk 链接）
> > 2. 通过 updater 安装 f5a 和 rime 插件
> > 3. 在 f5a 设置中的「插件」确认 rime 插件已经成功加载
> > 4. 在 f5a 的「输入法」设置中，添加「中州韵」
> > 5. 点击「中州韵」旁边的齿轮，再点击「用户数据目录」，确认用户目录的位置
> > 6. 把配置拷贝到用户目录中
> > 7. 切换点击🌐图标切换输入法到「中州韵」，自动部署，完成后应该可以使用
> 
> 请问这是什么APP？同文的更新app吗

跟同文无关，Android 上另一个 Rime 解决方案。

**Comment by ksqsf** [comment]
目前做了如下改进：

1. 词库中删除所有可能产生警报的词条，部署也不再误报警告。
2. 内置了同文需要的 prelude 文件，可以直接安装部署。

至于同文或小企鹅与手机的兼容性问题，就非本项目所能及了。因此认为该议题已完结。如有进一步的问题，可继续回复或 reopen。
