### ISSUE TITLE
能不能把moran方案构建在fcitx5的rime插件里面

### ISSUE THREAD

**Issue by shuen2023** [ksqsf/rime-moran#28]
这针对无法访Android/data的用户。rime插件默认的用户路径是在data目录下。似乎不能通过设置更该。可否直接编译斤rime插件使其在安装后就可使用。无需进一步更该。

**Comment by ksqsf** [comment]
data目录问题向f5a开发者反映比较好，毕竟可能是个共性问题。

**Comment by shuen2023** [comment]
> data目录问题向f5a开发者反映比较好，毕竟可能是个共性问题。

嗯。看来这个请求不太好实现。好在我通过在另一个手机上导出数据到正在用得的手机上导入算是能用了。但这个辅码有些情况着实让我不知该怎么打。比如独照我想要独招，我输入duvkk和duvkf都不对。。惆怅 。。

**Comment by ksqsf** [comment]
这个是因为 rime 在没有词的时候，会优先把 3+2 排在前面而不是 2+3（你打 duqvkf 或造出这个词后就没问题了）。在电脑上按 tab 可以快速修正，手机上我暂时也没有办法，只能选选字了。

**Comment by shuen2023** [comment]
> 这个是因为 rime 在没有词的时候，会优先把 3+2 排在前面而不是 2+3（你打 duqvkf 或造出这个词后就没问题了）。在电脑上按 tab 可以快速修正，手机上我暂时也没有办法，只能选选字了。

好吧。谢谢！
