### ISSUE TITLE
如何自定义微软双拼方案

### ISSUE THREAD

**Issue by lihuacai168** [ksqsf/rime-moran#30]
在微软双拼和自然码双拼的差异如下：
```yaml
# 为 R 增加 er 映射
# - xform/[uv]an$/R/
- xform/er|[uv]an$/R/

# 为 Y 增加 v 映射，并移除 ing 映射
# - xform/ing$|uai$/Y/
- xform/v|uai$/Y/

# 添加 ; 映射
- xform/ing$/;/

# 将 O 作为零声母填充
- xform/^([aoe].*)$/O$1/
```

我应该修改哪个配置来实现这些功能呢

**Comment by ksqsf** [comment]
基本方法是修改 algebra 中的映射，但是有两个需要注意的点：

1. 本方案的词库是直接使用双拼编码的，因此不能在拼音编码上做拼写运算，只能直接修改双拼编码
2. 微软方案含有分号，因此需要做三件事：（0）在`speller/alphabet`中增加`;`（1）对原本的运算表达式做一定修改 （3）去除分号次选功能

(1) 对拼写运算的修改。下面是个不完整的例子，

```
- xlit/;/§/            # 先把词库中的原来的 ; 分隔符转换成 § 分隔符

# 添加一些双拼映射规则
# 在编写规则时注意映射规则是从上往下顺序执行的
- xform/^an§/oj§/     # 如本行的意思是把 an 双拼码全部修改成 oj
- xform/^ah§/oh§/
- xform/^en§/of§/
- xform/^(\w)y§/$1§/  # 把所有的 Xy 修改成 X;
# ... 剩下的需要你来补充了

# 原本的映射规则 
# (1)把原本的分号改成上面的 `§`
# (2)音码部分的 `\w` 要替换成 `.` ，不然匹配不到分号
- derive/^(.+)§(\w)(\w)$/$1$2$3o/ # 全碼 YYXXo
- abbrev/^(.+)§(\w)(\w)$/$1$2$3/  # 降低 YYXX 優先級
- derive/^(.+)§(\w)(\w)$/$1$2/    # 構詞可以用 YYX
- derive/^(.+)§(\w)(\w)$/$1/      # 構詞可以用 YY
```

（2）去除分号次选功能需要删去方案中原本的这两行：

- `engine` 设置中的 `lua_processor@*moran_semicolon_processor`
- `key_binder` 设置中的 `{when: has_menu, accept: semicolon, send: "2"}`

上述设置对 `moran.schema.yaml` 和 `moran_sentence.schema.yaml` 是通用的。

---

字词模式码表 `moran_fixed.dict.yaml` （也就是主模式中的简码）无法使用拼写运算修改。根据具体需求，可选择一个较省事的解决方法：

1. 如果只用「整句」方案，可以不管这个码表。Done!
2. 如果主要使用主模式，可以只保留单字，然后把单字编码的前两码更新一下即可。
3. 如果也经常使用字词模式，或者完全不想手动处理，那可以使用 tools/schemagen.py 工具重新生成一份 `moran_fixed.dict.yaml`，不过这需要编写一点 Python 代码。schemagen.py 的用法可以参考 tools 目录下的 README 和 [这个 wiki 页面](https://github.com/ksqsf/rime-moran/wiki/%E6%9B%BF%E6%8F%9B%E8%BC%94%E5%8A%A9%E7%A2%BC)。

**Comment by lihuacai168** [comment]
> 基本方法是修改 algebra 中的映射，但是有两个需要注意的点：
> 
> 1. 本方案的词库是直接使用双拼编码的，因此不能在拼音编码上做拼写运算，直接映射双拼编码更容易
> 2. 微软方案含有分号，因此需要做三件事：（0）在`speller/alphabet`中增加`;`（1）对原本的运算表达式做一定修改 （3）去除分号次选功能
> 
> (1) 对拼写运算的修改。下面是个不完整的例子，
> 
> ```
> speller:
>   algebra:
>     - xlit/;/§/            # 先把词库中的原来的 ; 分隔符转换成 § 分隔符
> 
>     # 添加一些双拼映射规则
>     # 在编写规则时注意映射规则是从上往下顺序执行的
>     - xform/^an/oj/     # 如本行的意思是把 an 双拼码全部修改成 oj
>     - xform/^ah/oh/
>     - xform/^en/of/
>     - xform/^(\w)y/$1;/  # 把所有的 Xy 修改成 X;
>     # ... 剩下的需要你来补充了
> 
>     # 方案自带的映射规则也要修改
>     # (1)把原本的分号改成上面的 `§`
>     # (2)音码部分的 `\w` 要替换成 `.` ，不然匹配不到分号
>     - derive/^(.+)§(\w)(\w)$/$1$2$3o/ # 全碼 YYXXo
>     - abbrev/^(.+)§(\w)(\w)$/$1$2$3/  # 降低 YYXX 優先級
>     - derive/^(.+)§(\w)(\w)$/$1$2/    # 構詞可以用 YYX
>     - derive/^(.+)§(\w)(\w)$/$1/      # 構詞可以用 YY
> ```
> 
> （2）去除分号次选功能需要删去方案中原本的这两行：
> 
> * `engine` 设置中的 `lua_processor@*moran_semicolon_processor`
> * `key_binder` 设置中的 `{when: has_menu, accept: semicolon, send: "2"}`
> 
> 上述修改对 `moran.schema.yaml` `moran_sentence.schema.yaml` 是通用的。（辅筛方案 `moran_aux.schema.yaml` 只需要映射双拼编码即可，不用管词库自带的辅助码。）
> 
> 字词模式码表 `moran_fixed.dict.yaml` 或 `moran_fixed_simp.dict.yaml` （也就是主模式中的简码）无法直接使用拼写运算修改。根据具体需求，可选择一个较省事的解决方法：
> 
> 1. 如果只用「整句」或「辅筛」方案，可以不管这个码表。Done!
> 2. 如果主要使用主模式，可以只保留单字，然后把单字编码的前两码更新一下即可。——这个情形可以使用拼写运算，复用上面已有的规则能省点力。
> 3. 如果也经常使用字词模式，或者完全不想手动处理，那可以使用 tools/schemagen.py 工具重新生成一份字词码表替换现有的 `moran_fixed.dict.yaml` 或 `moran_fixed_simp.dict.yaml` ，不过这需要编写一点 Python 代码用来把拼音转换成微软双拼（应该不难，可以直接修改现有的 zrmify.py）。schemagen.py 的用法可以参考 tools 目录下的 README 和 [这个 wiki 页面](https://github.com/ksqsf/rime-moran/wiki/%E6%9B%BF%E6%8F%9B%E8%BC%94%E5%8A%A9%E7%A2%BC#3-%E7%94%9F%E6%88%90%E7%B0%A1%E7%A2%BC%E8%A1%A8)。

少了这个文件
```shell
# rikasai @ huacai-mbp in ~/Library/Rime/tools on git:main x [20:32:23] 
$ python3 ./schemagen.py --auxiliary-code=tiger --pinyin-table=data/pinyin_simp.txt gen-fixed --charset=data/simp_chars.txt --input-dict=data/simp_words.txt > fixed.txt
Traceback (most recent call last):
  File "/Users/rikasai/Library/Rime/tools/./schemagen.py", line 449, in <module>
    handle_gen_fixed()
  File "/Users/rikasai/Library/Rime/tools/./schemagen.py", line 279, in handle_gen_fixed
    for ac in to_auxiliary_codes(c):
  File "/Users/rikasai/Library/Rime/tools/./schemagen.py", line 72, in to_auxiliary_codes
    auxiliary_table = read_txt_table('data/tigerdb.txt')
  File "/Users/rikasai/Library/Rime/tools/./schemagen.py", line 45, in read_txt_table
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/tigerdb.txt'
(Rime) 
```

**Comment by ksqsf** [comment]
你忘了做第0步：把 `;` 加到 `speller/alphabet` 里。

```
speller:
  alphabet: abcdefghijklmnopqrstuvwxyz;
  initials: abcdefghijklmnopqrstuvwxyz
```

**Comment by lihuacai168** [comment]
正常输入ing是ok的  
使用反查的时候，比如输入`y;`然后再输入`反查辅码就有问题了，这个应该怎么解决呢

<img width="148" alt="image" src="https://github.com/ksqsf/rime-moran/assets/11568297/257f9c13-69e6-400b-8aa9-65d0e0027115">

**Comment by ksqsf** [comment]
<img width="614" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/68f15771-85db-4fdc-ba7e-91c302f45185">

修改一下 reverse_universal 的正则，目前的写法不接受分号

**Comment by lihuacai168** [comment]
表达式改为```(^(`[a-z`]+))|(^([a-z;]{2}(`[a-z`]?|[a-z`]`)))```，验证正则表达式是这样，可以匹配到
```
l;`
```
![image](https://github.com/ksqsf/rime-moran/assets/11568297/08b072b0-73a5-4c11-ae8f-309f04295c5b)

但是重新部署之后，还是没有实现反查功能

**Comment by ksqsf** [comment]
噢，这个还得修改 `moran_reverse.schema.yaml` 里的规则。

和之前一样，把 `;` 换掉，然后把音码部分替换成 `.`。

<img width="371" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/465265d7-e6f2-42a7-8351-5fc34d2abf48">

**Comment by lihuacai168** [comment]
> 噢，这个还得修改 `moran_reverse.schema.yaml` 里的规则。
> 
> 和之前一样，把 `;` 换掉，然后把音码部分替换成 `.`。
> 
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/23358293/290973029-465265d7-e6f2-42a7-8351-5fc34d2abf48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDI1NjgsIm5iZiI6MTcwMjcwMjI2OCwicGF0aCI6Ii8yMzM1ODI5My8yOTA5NzMwMjktNDY1MjY1ZDctZTZmMi00MmE3LTgzNTEtNWZjMzRkMmFiZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA0NTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NWI2ZTBhMDZiNjA2NmYyNzBmODI2NTU2MjUyODJiNjQ1YzZiMGRkYWVhNzczMWRhYWVhZThlYWY5NTRjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JGFW2DD9Bk0xZCEzE4B1MBeSnbZJS01wpcmT5-YInHs">

可以给参考一个例子吗？把`;`替换成`.`是不ok的
![image](https://github.com/ksqsf/rime-moran/assets/11568297/bcf0672a-c520-4e92-b8b7-1b06204bdfc2)

**Comment by ksqsf** [comment]
跟之前的改法一样啊

<img width="429" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/9a02e138-2350-491d-a41a-2dfe97c69ff8">

**Comment by ksqsf** [comment]
上面这个例子没写全，需要注意一下这个运算和 `moran.schema.yaml` 里一样是直接在词库编码上运算的，你需要把之前写好的 自然码→微软双拼 的规则复制到这里。

<img width="397" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/9b7b7977-473b-43f4-b2a8-a6edfcebd640">


<img width="547" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/e348671e-a7ca-44a3-b646-d356ec1d024e">

**Comment by lihuacai168** [comment]
> 上面这个例子没写全，需要注意一下这个运算和 `moran.schema.yaml` 里一样是直接在词库编码上运算的，你需要把之前写好的 自然码→微软双拼 的规则复制到这里。
> 
> <img alt="image" width="397" src="https://private-user-images.githubusercontent.com/23358293/290973581-9b7b7977-473b-43f4-b2a8-a6edfcebd640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDM1MDcsIm5iZiI6MTcwMjcwMzIwNywicGF0aCI6Ii8yMzM1ODI5My8yOTA5NzM1ODEtOWI3Yjc5NzctNDczYi00M2Y0LWIyYTgtYTZlZGZjZWJkNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA1MDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MmNjN2Q4MWU2NTYwN2ViNDY5Mjc4NDZhYTFiNDllOThlYjE3YWVlNWRjMTg5OWE1ZWQ0MjMyMTMxMDdlMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cbngHKGvR99uhytysIep6UlJwN0SDSvLr-t7x-oYias"> <img alt="image" width="547" src="https://private-user-images.githubusercontent.com/23358293/290973573-e348671e-a7ca-44a3-b646-d356ec1d024e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDM1MDcsIm5iZiI6MTcwMjcwMzIwNywicGF0aCI6Ii8yMzM1ODI5My8yOTA5NzM1NzMtZTM0ODY3MWUtYTdjYS00NGEzLWI2NDYtZDM1NmVjMWQwMjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA1MDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZTQxZmZlNzdhN2EwZDgzZjc3ZDY1MWY3YWZmYWIyN2FiNThmMDA3MzZiMWE5NjQzOGI1YjdiZmUxMTMxMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.evdrLJil5jJC4AYDYIbK0YW3ZPxG6ioJVVm9OJcp8PQ">

嗯嗯，通过把原来自然码修改的地方复制过来是ok了。  
现在自然码转微软需要修改好几个地方，有什么更好的办法抽取出来，弄成配置，放在同一个地方统一修改吗
![image](https://github.com/ksqsf/rime-moran/assets/11568297/fdc39642-8ed7-487b-99aa-291312342922)

**Comment by ksqsf** [comment]
需要把 algebra 拆分成几个部分，然后用 __patch __append 等特殊语法合并起来。遗憾的是没有 __prepend 操作，会比较麻烦。

参看 https://github.com/rime/home/wiki/Configuration

**Comment by ksqsf** [comment]
自 https://github.com/ksqsf/rime-moran/commit/10e11426da1c68437fc9701ddecef4df548dc18a 起，可以在 moran.yaml 中的 algebra/user_sentence_top 中统一定义 algebra 了，会同时在所有方案中生效。
