### ISSUE TITLE
设备同步资料问题，切换到其他非魔然方案，具体应该是什么样操作呢

### ISSUE THREAD

**Issue by lihuacai168** [ksqsf/rime-moran#31]
这里说的切换到非魔然方案，具体的操作步骤应该是怎么样的。  
麻烦给一个具体的参考案例
<img width="981" alt="image" src="https://github.com/ksqsf/rime-moran/assets/11568297/496ca79a-e28e-40e0-9db4-17b3ba2da30c">

**Comment by ksqsf** [comment]
比如切换到「朙月拼音」之类的。

用户词库 `moran.userdb` 被 `moran`, `moran_sentence`, `moran_aux` 共享，只要不是这些就行。

**Comment by lihuacai168** [comment]
> 比如切换到「朙月拼音」之类的。
> 
> 用户词库 `moran.userdb` 被 `moran`, `moran_sentence`, `moran_aux` 共享，只要不是这些就行。

类似这样是ok的，对吗
<img width="1190" alt="image" src="https://github.com/ksqsf/rime-moran/assets/11568297/8625e70e-9e9c-4b13-81ea-ba81a4f304b9">

**Comment by ksqsf** [comment]
直接 ctrl-` 切换就行
