### ISSUE TITLE
分号次选时，将输入框的每次选择都次选了

### ISSUE THREAD

**Issue by Kelatte** [ksqsf/rime-moran#34]
比如输入“nihknihk”，想要输入“妳好你好”，但是按下“；”后两次“nihk”选择都到次选了，得到“妳好妳好”

**Comment by ksqsf** [comment]
感谢反馈，不过我这里没能复现，如果有可以复现的案例的话不胜感激。如果很长时间没更新的话，可以尝试手动替换更新一下 [moran_semicolon_processor.lua](https://github.com/ksqsf/rime-moran/blob/main/lua/moran_semicolon_processor.lua)，之前修复过一次 bug。

https://github.com/ksqsf/rime-moran/assets/23358293/ebc560cf-cb53-4e37-9ffb-606669cc647f

**Comment by Kelatte** [comment]
感谢。我再试了几次发现只有moran方案会出现该情况，又发现了分号恰好被当作两次次选，是lua中把relase事件也处理了。 #36，这个PR能解决我的问题。

这个输入方案很好，感谢你们的维护。

**Comment by ksqsf** [comment]
明白了，这是因为 macOS 上不会产生 key release 事件导致我之前一直没发现这个问题。谢谢 PR！
