### ISSUE TITLE
中文输入状态下，输入大小写混合的英文单词，会改变字母顺序，这个该如何解决？

### ISSUE THREAD

**Issue by liangkaichun** [ksqsf/rime-moran#38]
一直习惯在中文状态下连续输入英文单词，回车直接上屏，但最近发现如果做大小写混合的时候，比如“iOS”这样的，会变成“oiS”

**Comment by ksqsf** [comment]
这是一个额外的功能（输入大写字母可追加辅助码到上一个音节末尾）的副作用，如果感到困扰可以禁用该功能。

新版配置：删去 schema 中 key_binder 中的 `moran_capital_for_last_syllable` 即可。

https://github.com/ksqsf/rime-moran/blob/a20de7915d8694cb0224dc536b3612b4ebba5a5f/moran.schema.yaml#L233

旧版配置：删去 schema key_binder 中这一坨即可。

https://github.com/ksqsf/rime-moran/blob/9b4c0eeaac4b36826ac5a3b8c72a2829102e06ec/moran.schema.yaml#L234-L260

**Comment by liangkaichun** [comment]
竟然还有这个功能，之前不知道，试用了一下，还挺方便，我保留这个设置了，谢谢！
