### ISSUE TITLE
“驭”字的全码没有出现在候选列表中

### ISSUE THREAD

**Issue by zzm-note** [ksqsf/rime-moran#39]
如题
“驭”字全码yu[my]输入后，字不见了

**Comment by ksqsf** [comment]
你好，可尝试一下输入 yumyo，应该能找到

<img width="138" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/7b69d9c3-e356-48ef-9e74-02ce483c1998">

单字全码需要多加一补码 `o`。这种设计是为了避免单字和词组争抢编码位。

另可参考[教程第三节](https://github.com/ksqsf/rime-moran/wiki/%E6%95%99%E7%A8%8B#%E5%85%B6%E4%B8%89%E6%9B%B0%E5%96%AE%E5%AD%97%E8%BC%B8%E5%85%A5%E6%96%B9%E5%BC%8F)

**Comment by zzm-note** [comment]
> 你好，可尝试一下输入 yumyo，应该能找到
> 
> <img alt="image" width="138" src="https://private-user-images.githubusercontent.com/23358293/316241132-7b69d9c3-e356-48ef-9e74-02ce483c1998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMDA4NTYsIm5iZiI6MTcxMTIwMDU1NiwicGF0aCI6Ii8yMzM1ODI5My8zMTYyNDExMzItN2I2OWQ5YzMtZTM1Ni00OGVmLTllNzQtMDJjZTQ4M2MxOTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDEzMjkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZTMxZDdiYzdhNDczNDY3NDllZTM0NjZiYmIxM2JkZjQwNTk2OTEyZTZkOWNlNGIwNWY3YmFhYzc1NWVmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j9ndtlBwdMGANQ9wjE9ATWRZUAJxtCootEpnphsHBko">
> 单字全码需要多加一补码 `o`。这种设计是为了避免单字和词组争抢编码位。
> 
> 另可参考[教程第三节](https://github.com/ksqsf/rime-moran/wiki/%E6%95%99%E7%A8%8B#%E5%85%B6%E4%B8%89%E6%9B%B0%E5%96%AE%E5%AD%97%E8%BC%B8%E5%85%A5%E6%96%B9%E5%BC%8F)

确实可以:)
不过输入全码后不加补码找不到还是比较诡异

**Comment by ksqsf** [comment]
的确，我把教程中的描述修改了一下：如果 yyxx 是合法的词组编码，则该字不会显示在候选中。

具体的行为决定于拼写运算产生的音节类型

https://github.com/ksqsf/rime-moran/blob/533ee751c0ec8c69a7390dfded401d8677c0a450/moran.yaml#L34

默认设置为 `abbrev`，若修改为 `fuzz` 则可以把单字和词语混在一起显示。如果喜欢这种，可手动修改一下。
