### ISSUE TITLE
無法選符號

### ISSUE THREAD

**Issue by RomaYun323** [ksqsf/rime-moran#42]
![image](https://github.com/ksqsf/rime-moran/assets/75065161/9a66c77b-afa4-41db-b9af-57ed88a36550)
輸入`/`無法繼續按`/`向下選擇半角、全角、除號
請問這是正常的嗎？其他標點符號可以。
謝謝

**Comment by ksqsf** [comment]
是正常的，這是最近的一個變更（允許使用 yyxx/ 輸入單字）的副作用：https://github.com/ksqsf/rime-moran/commit/6684706edb9274463ae6d3d6ee2795778a9b03b4

如果不需要該功能，可將 / 從 speller/alphabet 中刪除。

**Comment by RomaYun323** [comment]
感謝
