### ISSUE TITLE
简体fixed词库 moran_fixed_simp.dict.yaml 需打磨

### ISSUE THREAD

**Issue by bosbyj** [ksqsf/rime-moran#43]
审核词库时发现问题，报告如下：

- 简体版字词打法 s 简码变成【随】，繁体版为【三】词频更高，更科学
- 简体版字词打法 sa 没有编码

moran_fixed_simp.dict.yaml
```
认贼作父	rzzf
随	s	svez
卅	saa
撒把	saba
洒遍	sabm
撒播	sabo
萨	saci
洒	sad
```

moran_fixed.dict.yaml
```
認賊作父	rzzf
三	s	sjaa
撒	sa
撒把	saba
灑遍	sabm
撒播	sabo
薩	sac
蔡	sacj
```

**Comment by ksqsf** [comment]
感谢指出，已做相应调整。

（该 issue 会长期打开，便于收集意见和反馈。）

**Comment by ksqsf** [comment]
这里备注一下我优化繁体码表的原则，如果之后有人打算对简体码表做进一步优化的话可供参考：

1. 单字编码只选取 chars 表中已有的编码；若增加无理码（chars表中没有的编码），需明确标出，并统一放置在文件末，便于用户删除
2. 单字编码尽量不取容错码，而是取正码（即 chars 表中靠前的编码），细则：
   - 一个部件若有多个容错编码，则只取正码，不留容错码（如 亠 w d 只取 w，不取 d）
   - 一个字若有多种拆分，则两种拆分法均可保留
3. 一二简不出全，三简让全

**Comment by jack2game** [comment]
`缓存	hc`
优先于
`好	hc`

**Comment by ksqsf** [comment]
@jack2game 这个是转换小鹤双拼后产生的问题（自然码里 hc 是空码）。建议从 fixed 表中直接删除该词。

**Comment by jack2game** [comment]
謝謝。是否考慮可以將所有單字放置於詞語之前，以此盡量避免類似的情況？如果可以的話，我也很樂意提交PR，謝謝🙏

**Comment by ksqsf** [comment]
> 謝謝。是否考慮可以將所有單字放置於詞語之前，以此盡量避免類似的情況？如果可以的話，我也很樂意提交PR，謝謝🙏

单字不能全放在词语之前，一些生僻字频率并不高。但是我觉得可以把简词全部移到主码表之后。

**Comment by king-ta** [comment]
pe 浌 生僻字，可选 普洱、配额等
kz 克  无理码？剋
bp 兺  生僻字，可选 不怕、背叛等
pp 丶  无码  ， 可选 品牌、批评 
fc 覅 生僻字，可选 讽刺、粉刺
np 嫩 无理码？黁
nb 耨 生僻字， 牛逼 
yz 越 无理字，样子、原则
wk 味 无理字，
---------
vy 拽  不常用，这样 特别常用
zd 自动，知道  也比较常用
st 色图， 这。。。。。 洒脱
ww 呜呜，问问，往往

**Comment by bosbyj** [comment]
> 几个意见
> 
> pe 浌 生僻字，可选 普洱、配额等 kz 克 无理码？剋 bp 兺 生僻字，可选 不怕、背叛等 pp 丶 无码 ， 可选 品牌、批评 fc 覅 生僻字，可选 讽刺、粉刺 np 嫩 无理码？黁 nb 耨 生僻字， 牛逼 yz 越 无理字，样子、原则 wk 味 无理字，
> 
> vy 拽 不常用，这样 特别常用 zd 自动，知道 也比较常用 st 色图， 这。。。。。 洒脱 ww 呜呜，问问，往往

st nb!

**Comment by ksqsf** [comment]
大部分细调应该已经完成。
