### ISSUE TITLE
对补码5码的思考「增加 YYXX/ 編碼 (實驗性)」

### ISSUE THREAD

**Issue by bosbyj** [ksqsf/rime-moran#45]
f大您好

「魔然」默认模式下的痛点是，我打4码全码，首页5个候选，第1个是词语，另外4个是和全码不关联的字。

比如

jwrg 佳 jw人圭，出现

1. 假仍
2. 假
3. 家
4. 加
5. 价

或者 jnjn/，出现5个词语

建议思路：

充分利用fixed词库，四字简码位置咱们用上，我打jwrg的时候，

第1候选为词语
第2候选默认为全码单字，记录在fixed词库，带闪电标记［即 置顶在第2位，可以分号直接上屏］
第3候选，如果有词语，就放词语
以此类推

jwrg
1. 假仍
2. 佳⚡
3. 假
4. 家
5. 加

好处：
1. 第5次按键 ； 直接上屏，相比o/+ 空格，少输入一个键
6. 候选中能直接看到4码全码字，减少挫败感

**Comment by ksqsf** [comment]
很好的想法！已增加该功能

**Comment by bosbyj** [comment]
太强了，已经测试ok。

抽空多学习老大的注释，理解思路。我还没写过lua。
