### ISSUE TITLE
最新的action版本，在安卓上的小企鹅输入法中，生僻字显示还是有问题

### ISSUE THREAD

**Issue by liangkaichun** [ksqsf/rime-moran#47]
最新版已经有改善，但还是有部分生僻字没有被过滤：
![小企鹅](https://github.com/ksqsf/rime-moran/assets/3862788/200b9436-fc9c-4521-9d10-edb3f41bb54c)

**Comment by ksqsf** [comment]
请问这个是什么字体？我之后跟现在的字集取一下交集。

**Comment by liangkaichun** [comment]
小米手机默认的字体：MiSans

**Comment by ksqsf** [comment]
[31c0ee6](https://github.com/ksqsf/rime-moran/commit/31c0ee6e906667eb977391716876c9d40cdaa33d) 据 MiSans 减少了约 5000 字。

**Comment by liangkaichun** [comment]
如果是字体的问题，我觉得就不用改了，现在这个情况已经影响不大了。

**Comment by liangkaichun** [comment]
动作太快了，谢谢！
