### ISSUE TITLE
不知是bug还是feature，yz 越 ？wk 味？

### ISSUE THREAD

**Issue by king-ta** [ksqsf/rime-moran#48]
yz 会打出越来，wk 会打出味

**Comment by king-ta** [comment]
是mac 繁体版
windows 简体打包版没有这个问题。

**Comment by ksqsf** [comment]
这是特意加的无理码。yz手感强于ytz，wk是为了避重+手感，同理还有个wkw围。

不过感谢提醒，之前混在前面的码表里了，现在挪到无理码部分。
