### ISSUE TITLE
單字模式quick_code_indicator與enable_aux_hint無法同時啓用

### ISSUE THREAD

**Issue by jack2game** [ksqsf/rime-moran#49]
`quick_code_indicator: "⚡️"` + `enable_word_filter: false` = ✅
`quick_code_indicator: ""` + `enable_word_filter: true` = ✅
`quick_code_indicator: "⚡️"` + `enable_word_filter: true` = `quick_code_indicator` no longer works

**Comment by jack2game** [comment]
另外，在weasel小狼毫中啓用`enable_word_filter: true`似乎沒有效果。倉輸入法目前正常

**Comment by liangkaichun** [comment]
只是不显示闪电图标，固顶的字和词还是在的。

要是能给固顶闪电词加个可以关闭的开关就完美了
