### ISSUE TITLE
字集过滤的性能问题

### ISSUE THREAD

**Issue by ksqsf** [ksqsf/rime-moran#51]
reposted https://github.com/ksqsf/rime-moran/discussions/44#discussioncomment-9211320

**Comment by liangkaichun** [comment]
测试了一下，CPU占用明显降低了，输入的时候，CPU占用率一直可以保持在20%以下，也没有卡顿的感觉了，非常感谢！

**Comment by liangkaichun** [comment]
长时间使用，CPU占用率还是会变高，我这边最高能到40%+，比较奇怪。
当CPU占用率高的时候，会有一些卡顿的感觉。

**Comment by ksqsf** [comment]
自己用着感觉没啥问题了。之后给rime写一个C++实现的。。。

**Comment by liangkaichun** [comment]
我这边还是会有一些卡顿，尤其是连续用一段时间以后。

另外，不太理解为什么，在浏览器中输入，卡顿感更严重一些。

**Comment by liangkaichun** [comment]
看到鼠须管官方发布了0.18版本，可是这个版本也没有包含 charset_filter，难道后续鼠须管就不再支持这个 charset_filter了吗？

**Comment by ksqsf** [comment]
不管是 librime 内置的基础版 charset_filter 还是 charcode 插件的增强版其实都不够用（实现方法都是转换 encoding），不能自定义字集。

目前 Lua 的实现先作为一个临时解法，之后我会给 librime PR 一个实现方法与 Lua 版本类似的 C++ 版，应该就能彻底解决问题了。
