### ISSUE TITLE
openSUSE Tumbleweed fcitx5-rime 魔然本體默認只有英語，註釋掉英語混輸後無輸入候選框且只能打英文

### ISSUE THREAD

**Issue by OriginCode** [ksqsf/rime-moran#54]
librime: 1.10.0+git20240229.4ee471e-76.4
嘗試了 plum 安裝和手動解壓安裝都是這樣，整句模式沒問題。

**Comment by ksqsf** [comment]
moran 方案强依赖于 lua 插件（`moran_sentence` 和 `moran_fixed` 则不强依赖），请确认是否已安装 librime-lua / librime-plugin-lua 等类似插件。

（检查了一下 https://software.opensuse.org/package/librime-lua ，Tumbleweed 应该已有相应包可直接安装）

**Comment by OriginCode** [comment]
> `moran` 方案强依赖于 lua 插件（`moran_sentence` 和 `moran_fixed` 则不强依赖），请确认是否已安装 librime-lua / librime-plugin-lua 等名字的包。
> 
> （检查了一下 https://software.opensuse.org/package/librime-lua ，Tumbleweed 应该已有相应包可直接安装，而且足够新）

確實好了，感謝。
順帶一提，也許在 Wiki 附個安裝教程會更好？

**Comment by ksqsf** [comment]
感謝建議，增加了安裝信息頁面 https://github.com/ksqsf/rime-moran/wiki/Installation
