### ISSUE TITLE
schemagen 优化windows兼容性

### ISSUE THREAD

**Issue by bosbyj** [ksqsf/rime-moran#55]
schemagen大量依靠print函数输出txt，然后通过>重定向到txt。

然而，windows的terminal utf8支持很差。经常报错UnicodeEncodeError，感觉自己回到了python2的年代。

周末思考

windows方面，terminal需要 chcp 65001

schemagen代码，检测运行环境为win，则暴力猴子补丁两个内置函数

print(文本, encoding='utf-8')
open(文本, w/r, encoding='utf-8')

**Comment by ksqsf** [comment]
应该不用手动加 encoding 参数，设置一下 `PYTHONUTF8=1` 环境变量 或传递 `-X utf8` 参数给 python 就可以了。

**Comment by bosbyj** [comment]
win11下永久设置cmd编码为utf-8

- 首先找到设置页面
- 搜索地区，并点击更改国家或地区
- 选择管理语言设置
- 选择更改系统区域设置
- 勾选Beta版: 使用Unicode UTF-8 提供全球语言支持，重启生效，问题解决
