### ISSUE TITLE
默認模式下中英混合輸入時；只選中文

### ISSUE THREAD

**Issue by RomaYun323** [ksqsf/rime-moran#56]
魔然默認模式下，中英文混輸「；」選字會輸出「日麼」
候選項同時有中英文時，分號會輸出排除英文的次選
整句模式無此問題
![image](https://github.com/ksqsf/rime-moran/assets/75065161/509131ef-86d0-4fdd-810f-ac96bfb5a123)

**Comment by ksqsf** [comment]
其實這是個 feature，默認模式專門引入了一個叫做 `moran_semicolon_processor` 的東西，用於跳過「非漢字」的選項，主要目的是用來跳過 emoji。

不過你提到的英文候選似乎保留下來也沒問題！已經推送了一個fix。
