### ISSUE TITLE
置顶词显示错误？

### ISSUE THREAD

**Issue by zzm-note** [ksqsf/rime-moran#63]
![image](https://github.com/ksqsf/rime-moran/assets/25860330/0053ceff-6729-46f0-b815-7f9d058af421)
最新的版本会出现首位候选词没有那个闪电符号的词汇，不知道是不是出bug了？有时候老是选错词

**Comment by ksqsf** [comment]
是个新功能，在 #45 引入的。

https://github.com/ksqsf/rime-moran/blob/main/moran.schema.yaml#L299

把 show_words_anyway 设置成 false 就可以关闭了。

这个功能主要是在手机上打长词比较方便，比如
<img width="306" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/dc741b4b-357c-4588-96a7-c26d0d67204e">
