### ISSUE TITLE
辅筛模式如何设置实现：三码的时候优先单字，四码优先词组

### ISSUE THREAD

**Issue by liangkaichun** [ksqsf/rime-moran#64]
最近切换到了辅筛模式，和我的输入习惯非常的匹配。

我不用简拼，但在三码的时候，经常会两字词优先，导致输入单字的效率比较低。如果是词组输入，我一定会把每个字都打全，所以当输入奇数个码的时候，希望是筛选单字模式，输入偶数个码的时候，是词组优先模式。

请问，这个该如何修改？

**Comment by ksqsf** [comment]
https://github.com/ksqsf/rime-moran/commit/374e101aabba5fb11dc4136b0ad96ccc6c6bc0d9 增加了三码优先单字

**Comment by bosbyj** [comment]
经查

辅筛 单字，貌似3码有效，4码全码单字，优先级会在2码拼音 用户词 之下

**Comment by bosbyj** [comment]
![image](https://github.com/ksqsf/rime-moran/assets/7922167/dd427218-5524-4d54-a81e-cfbfebee7e63)

首次打fur 并未出现以下文字

付
傅
伏
佛
俘
俯

每个字都输入一遍后，产生了用户词库userdb，就又出现了

![image](https://github.com/ksqsf/rime-moran/assets/7922167/79eb00a9-2bdb-4da5-add5-367ca7011eac)

**Comment by bosbyj** [comment]
思考后，发现符合逻辑。

最初的 辅筛，就是 把 2字词组，拎出一个到首位cand。

到3码单字模式，应该是要提前所有符合的三码字。但是由于是通过zrmdb产生的，不知道词频会不会有优化。

**Comment by ksqsf** [comment]
Feel free to reopen if the problem persists
