### ISSUE TITLE
辅助码造词似乎在ios的仓输入法上无法正常使用

### ISSUE THREAD

**Issue by pipiTan** [ksqsf/rime-moran#66]
只要收下了输入法，造的词就没了

**Comment by ksqsf** [comment]
可否提供一个案例呢？我用仓是正常的。

**Comment by pipiTan** [comment]
![IMG_2727](https://github.com/ksqsf/rime-moran/assets/18749923/98b2ae20-e772-4eca-b839-e46017eb09a4)
 
![IMG_2728](https://github.com/ksqsf/rime-moran/assets/18749923/fc5b605c-0bfb-4aff-b7e3-19b15ef81344)

fzfz原本首位是飞飞，fzfzo是肥肥，我没收起键盘时fzfz首位确实变成了后者，但是收起键盘再呼出，fzfz首位又变成飞飞了

**Comment by ksqsf** [comment]
我在我的手机上测试了一下，确实没有这个现象。猜测是因为仓没有成功写入用户词库，而键盘重启后读到了之前的用户词库。可以尝试一下这样的操作：

1. 首先杀掉仓
2. 然后删除 moran.userdb/LOCK

还有就是看看是不是在用最新版的仓，我用的是目前的商店版 2.6.1(1)。

**Comment by pipiTan** [comment]
> 我在我的手机上测试了一下，确实没有这个现象。猜测是因为仓没有成功写入用户词库，而键盘重启后读到了之前的用户词库。可以尝试一下这样的操作：
> 
> 1. 首先杀掉仓
> 2. 然后删除 moran.userdb/LOCK
> 
> 还有就是看看是不是在用最新版的仓，我用的是目前的商店版 2.6.1(1)。

我似乎找到问题了，我在switcher里改的任何东西只要重启键盘都会复原，应该是同一个问题，仓自己的问题。

不过应该如何杀掉仓呢，还有我也找不到lock这个文件，。

**Comment by pipiTan** [comment]
> 仓设置 → 文件管理 → 应用文件/键盘文件 → moran.userdb 里应该有 LOCK。删除后重启一下手机试试。

好像没有这个文件，但是我重启了，依然有这个问题，我继续排查一下。

**Comment by pipiTan** [comment]
> > 仓设置 → 文件管理 → 应用文件/键盘文件 → moran.userdb 里应该有 LOCK。删除后重启一下手机试试。
> 
> 好像没有这个文件，但是我重启了，依然有这个问题，我继续排查一下。
> 
> switcher里的东西改了重新呼出键盘还原了，我重装后还是有这个严重的问题。。。感觉暂时解决不了。




我找到问题所在了，要给仓完全访问的权限。
感谢你的帮助！

**Comment by ksqsf** [comment]
> 我找到问题所在了，要给仓完全访问的权限。

感谢！记录到 wiki 中了。
