### ISSUE TITLE
辅筛模式是否可以考虑加一个固定一级简码字的选项？谢谢

### ISSUE THREAD

**Issue by davidlauhn** [ksqsf/rime-moran#69]
有个不好的习惯，原版自然码的一级简码字，打习惯了，其它我都是用双拼全码，然后加辅助码，突然没了固顶的一级简码字，经常打错字，是否可以考虑给个选项开关？谢谢

**Comment by davidlauhn** [comment]
我只是下载了 moran.lua 覆盖了一下，刚才测试了一下，好像没有固顶，貌似只是因为我在修改 moran_aux.custom.yaml 输入过这些单字，从而使这些单字的候选位上升到了首位，因为重新部署后打 y 和 j 的时候，还是别的单字在首位，看了一下重新部署后的 build/moran_aux.schema.yaml ，又是生效的，有些疑惑

**Comment by ksqsf** [comment]
更新三个文件：moran.lua, moran_aux.schema.yaml, moran_fix_filter.lua

**Comment by davidlauhn** [comment]
哈，忘了看[这里](https://github.com/ksqsf/rime-moran/issues/69)的左侧了，perfect, thanks.

**Comment by davidlauhn** [comment]
改完后清空了用户词典，发现「辅筛模式」用 `fuulmouii v  ` 打不出来了，不知道哪里出了问题

**Comment by ksqsf** [comment]
可否提供下你的配置？

**Comment by ksqsf** [comment]
<img width="77" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/8f6460d5-0482-4d9c-88bf-fd4cc5be746f">

<img width="145" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/00cb8c2a-712d-46b0-bb22-dba34859dc09">

我试了下好像没问题（已确认你的一简配置生效）？要不把相关的 lua 全部替换一下试试？

**Comment by davidlauhn** [comment]
刚把lua全部替换了，还是一样，发现是个别的单字辅助码失效，比如「辅」、「试」，应该是因为「辅」的辅助码失效，所以打不出来「辅筛模式」，用的是小狼毫0.16.0.0

**Comment by ksqsf** [comment]
替换 lua 的时候是不是把 zrmdb.txt 给删掉了？

**Comment by davidlauhn** [comment]
并没有哦

**Comment by davidlauhn** [comment]
问题应该出在[三码单字优先](https://github.com/ksqsf/rime-moran/commit/374e101aabba5fb11dc4136b0ad96ccc6c6bc0d9)修改的moran_aux_translator.lua 引起的，我卸载重装了小狼毫nightly+20240525版，按照你上面提到的方法修改了一级简码字，用起来都没有问题，又更新了一下 moran_aux_translator.lua ，就出问题了，三码单字是优先了，一级简码字也没问题，可是出现了个别单字无法使用辅助码的问题，比如上面提到的 「辅」、「试」， moran_aux_translator.lua 退回20240525版就没有问题了
