### ISSUE TITLE
自定义 fixed.dict / fixed.schema 怎样实现出简让全？

### ISSUE THREAD

**Issue by bosbyj** [ksqsf/rime-moran#71]
请教k大，

我自用的fixed.dict词库，貌似开启不了moran/ijrq功能。出简让全只能在【魔然】里使用。

请问有何方法可以实现？自己在打磨自己的fixed码表。

**Comment by jack2game** [comment]
通過 https://github.com/ksqsf/rime-moran/blob/main/lua/moran_express_translator.lua 實現

此類問題並不是issue，煩請close issue並移步[討論版](https://github.com/ksqsf/rime-moran/discussions)

**Comment by bosbyj** [comment]
明白，感谢！
研究加上express translator是否可以实现。
先关闭了。
