### ISSUE TITLE
Unicode hints overwritten by enable_quick_code_hint

### ISSUE THREAD

**Issue by jack2game** [ksqsf/rime-moran#72]
When setting `enable_quick_code_hint` = `true`,  Unicode hints will no long work with characters that has quick codes.

For e.g.

![image](https://github.com/ksqsf/rime-moran/assets/16070158/ac4acc37-e040-4606-85ef-28f3eae937f7)

**Comment by ksqsf** [comment]
This is weird. The Unicode hint filter is placed AFTER the quick code hint, so there's no way QC hint overwrites it. I'll look into it.

**Comment by ksqsf** [comment]
fixed
