### ISSUE TITLE
通配符反差不起作用

### ISSUE THREAD

**Issue by ChaosPivot** [ksqsf/rime-moran#75]
使用通配符反查不起作用，但虎码、两分等方式可以正常使用。
<img width="294" alt="image" src="https://github.com/ksqsf/rime-moran/assets/3360460/29e9a1c6-85f0-411f-b14d-f6bb5276d1ab">

**Comment by ksqsf** [comment]
非常感谢反馈！是昨天引入的一个性能优化导致的问题，已经revert了
