### ISSUE TITLE
辅筛模式：四码两字词组，只展示一个高频词组在首位，其他默认不展示

### ISSUE THREAD

**Issue by liangkaichun** [ksqsf/rime-moran#76]
输入四码，正常应该有多个两字词组候选，但现在仅有一个最高频的两字词组展示在首位，后面都是单字，连续向后翻页，均没有其他两字词组出现，只能通过增加辅码来选择其他两字词。这个逻辑不对，输入四码，应该默认展示两字词组。

![image](https://github.com/ksqsf/rime-moran/assets/3862788/828cda38-d8a3-4036-b537-b3e012f20066)

**Comment by ksqsf** [comment]
请试试 https://github.com/ksqsf/rime-moran/blob/19c36d41370a830c9cd964be1cd7713e230e3022/lua/moran_aux_translator.lua

**Comment by liangkaichun** [comment]
四码只展示一个两字词组的问题解决乐，谢谢！

另外一个问题，如果四码存在单字，两字词组多次输入后也无法排到四码单字前，这是默认的逻辑，还是四码单字权重太高了的原因？

**Comment by liangkaichun** [comment]
![image](https://github.com/ksqsf/rime-moran/assets/3862788/0e694bfc-7a2e-4476-be3f-a988980fa2b3)

这个 惰 字，不知道为什么会出现在doxx这个编码下，看了单字词典，里面惰对应的编码是：doxo

**Comment by ksqsf** [comment]
应该是搞定了 https://github.com/ksqsf/rime-moran/blob/6284055ecf09f797c132eb5aa728b427f51776da/lua/moran_aux_translator.lua

**Comment by liangkaichun** [comment]
手机上用仓输入法测试了一下，修正了，谢谢

**Comment by ksqsf** [comment]
OK，那我就关闭这个issue了，还有问题的话可以reopen。
