### ISSUE TITLE
關於 pinyingen 裡的資料來源

### ISSUE THREAD

**Issue by eth3lbert** [ksqsf/rime-moran#83]
想請問 `tools/pinyingen.py` 裡頭用到的 `essay.raw` 以及 `luna.raw` 該如何取得呢？

**Comment by ksqsf** [comment]
pinyingen 是用来合并 essay.txt （词语和词频）和 luna_pinyin.dict.yaml （词语、读音、多音字分频）信息，产生 pinyin.txt 的。这两个数据文件都是 rime 自带的数据，pinyin.txt 已经 check in 到 tools/data 下了，所以你大概率不需要手动运行这个工具。

- essay.raw 就是 essay.txt, https://github.com/rime/librime/blob/6b1b41f53cd7fb8cd605c65cfb1e8d5c780f1308/data/minimal/essay.txt
- luna_pinyin.dict.yaml 来自朙月拼音, https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.dict.yaml

**Comment by ksqsf** [comment]
BTW，如果你想使用 schemagen，可以参考 https://rime-moran.gitbook.io/book/gong-ju/fang-an-sheng-cheng-gong-ju

**Comment by eth3lbert** [comment]
感謝回復，跟我猜想的一樣。

> pinyin.txt 已经 check in 到 tools/data 下了，所以你大概率不需要手动运行这个工具。

是的，目前還在研究階段而已，還沒實際上手使用，只是預防可能有需要調整詞庫/詞頻所以瞭解一下。
