### ISSUE TITLE
re的候选错误

### ISSUE THREAD

**Issue by zzm-note** [ksqsf/rime-moran#84]
![image](https://github.com/ksqsf/rime-moran/assets/25860330/1db7ecd8-24e1-4215-9bd2-86f9e6f71d77)
输入re，出现的第一位候选怎么是“不入耳”？是词库中写错了吗？

**Comment by ksqsf** [comment]
尴尬，可能是编辑码表的时候不小心删了个b……我今天重新传一下压缩包。

目前可以先手动编辑 moran_fixed_simp.dict.yaml 纠正该错误。

**Comment by jack2game** [comment]
目前`moran_fixed_simp.dict.yaml`中`簡碼碼長`<`文字數`的詞組（排除5字以及以上）

| 文字數 | 詞組   | 簡碼  | 簡碼碼長  |
| --- | ---- | --- | --- |
| 4   | 文件系统 | fs  | 2   |
| 4   | 举个例子 | jgl | 3   |
| 4   | 解决方案 | jjf | 3   |
| 4   | 解决方法 | jjf | 3   |
| 4   | 操作系统 | os  | 2   |
| 4   | 十六进制 | ulj | 3   |
| 4   | 输入输出 | uru | 3   |
| 4   | 文本文件 | wbw | 3   |
| 4   | 一心一意 | yxy | 3   |
| 3   | 二进制  | ej  | 2   |
| 3   | 不入耳  | re  | 2   |
| 2   | 感觉   | g   | 1   |
| 2   | 觉得   | j   | 1   |
| 2   | 可以   | k   | 1   |
| 2   | 没有   | m   | 1   |
| 2   | 自己   | z   | 1   |
