### ISSUE TITLE
最新版辅筛模式的单字辅码筛选召回有问题

### ISSUE THREAD

**Issue by liangkaichun** [ksqsf/rime-moran#89]
如果一个单字加上辅码后，仍然有很多候选项，辅筛模式下单字的召回不足，比如单字“羁”，输入jism，筛选不出来。向后翻页找到“羁”这个字，选择后，前面输入的辅码没有消失。

同样的情况，在输入词组造词的时候，也没有办法用辅码sm将“羁”筛选出来。

**Comment by ksqsf** [comment]
已修复。

**Comment by liangkaichun** [comment]
![IMG_0483](https://github.com/ksqsf/rime-moran/assets/3862788/0bea329e-1eb9-41da-a2ab-f180251cea33)

还是有一些音的字出不来，比如 xnj，忻j ，炘j 等

**Comment by liangkaichun** [comment]
请问：辅筛里为啥要限制辅码筛选返回单字的数量？ yj这个音下面的一些单字加上辅码也筛选不出来

如果完全放开PREFETCH_THRESHOLD的数量限制会有什么问题吗？

性能会下降？

**Comment by ksqsf** [comment]
速度会慢，不过我自己也没测过具体应该取多少（汗），目前的取法是「让高频字可以被筛选，低频字就不管了」。你可以尝试取一个更大的 PREFETCH_THRESHOLD，如果性能上没太大问题的话，那之后直接取个巨大的数字应该也行

**Comment by liangkaichun** [comment]
我直接将超过阈值时的break给注释掉了：
      if n_matched + n_unmatched > threshold then
--         break
      end

用了两天，性能上没问题，没有什么影响，一直有盯着CPU占用率和内存使用情况，都挺正常的。

**Comment by ksqsf** [comment]
感谢，那么我准备改成一个配置选项，默认无限制，觉得卡的可以自己设置一个上限
