### ISSUE TITLE
【优化建议】造词功能三字词优先声声声_而非声声声韵

### ISSUE THREAD

**Issue by Dr-Octopus-dev** [ksqsf/rime-moran#9]
我的建议是，优化一下，造三字词的时候，如果这三个字母没有被占用，优先使用声声声的编码，这样的好处是少一个编码用空格代替，坏处可能是造成造词规则不统一，造过的词需要额外记忆有无第四码，建议不很成熟，请蒻师帮忙考评一下

**Comment by ksqsf** [comment]
其實可以不用改造詞邏輯，修改 schema 把 fixed 下面的 enable_completion 改成 true 應該就可以了。

**Comment by Dr-Octopus-dev** [comment]
前几天又觉得，声韵声声是个更符合直觉的造词规则，因为打第一个字的时候会受条反影响刹不住车，打出韵母，这时候如果用我上述的规则，进可打三字词、二字词，退可加辅打单，何乐而不为？

**Comment by ksqsf** [comment]
目前的考虑：

1. 默认的 `moran_fixed` 方案需是 abcc：三字词三简刚好是 abc，更适合给默认模式使用。
2. 单独的 aabc 词库可以通过 import_table + encoder rules 让 rime 自动编码实现，从而可以避免一、二、四+字词的词库重复。
