### ISSUE TITLE
該如何新增一個注音反查功能到魔然裡？

### ISSUE THREAD

**Issue by eth3lbert** [ksqsf/rime-moran#93]
查到的方式都是基於拼音輸入法，比如：
- https://gist.github.com/kenming/5d4161c96592cbcd05f62cf1446a7a28#file-flypy_tw-schema-yaml-L167
- https://github.com/JeffChien/rime-flypyquick5/blob/ac8a9e5f7d4c0f28efb64f198c26f7ce395c2319/flypy_luna.schema.yaml#L100

不確定這在魔然裡是不是可以work或是最好的做法？

**Comment by ksqsf** [comment]
有這麼幾步：

1. 安裝一個注音 schema，添加到 schema/dependencies
2. 添加 reverse_lookup_translator@reverse_bopomofo
3. 添加 recognizer/patterns
4. 編寫 reverse_bopomofo，設置爲使用注音的 dictionary

Rime 是自帶注音方案的，可以考慮直接內置進來🤔 我來做一個

**Comment by ksqsf** [comment]
增加了一個基於 Rime 自帶的 `bopomofo` 方案（大千式佈局）的反查，只適合查單字，不能用於連續輸入。簡單用了下似乎能用，有問題的話請留言~

**Comment by eth3lbert** [comment]
實測基本上 work 的！
目前已知不 work 的是 `樣` 輸入 `ovyu;` 沒有出現提示：
<img width="136" alt="image" src="https://github.com/ksqsf/rime-moran/assets/2889664/386f8239-30d9-4379-a6d0-db1830091af9">




P.S. 希望補個飛鍵結束注釋對應其起始注釋至 fixed dict 中，這樣可以使用 `sed -i '/start comment/,/close comment/d'` 去刪除不需要的區塊
e.g.
起始:`# 飛鍵 qx -> qo` 
結束:`# 結束飛鍵 qx -> qo`

**Comment by ksqsf** [comment]
1. moran_sentence 中現在 u; 應該 OK 了。

2. 增加了「開始飛鍵」「結束飛濺」的註釋。

**Comment by eth3lbert** [comment]
確認 works!  thanks!
