### ISSUE TITLE
輔篩與 fixed

### ISSUE THREAD

**Issue by eth3lbert** [ksqsf/rime-moran#94]
經反查`實`顯示爲`ui[bg]`，但它在 fixed 中是 `uib` 這使得輸入 `uibg` 並不會直接對應到`實`，而是
<img width="235" alt="image" src="https://github.com/ksqsf/rime-moran/assets/2889664/7f0daf56-94d7-460e-9ebf-219463f5e073">
不確定這是 bug 還是限制？

直覺猜測需要補入 `uibg` 這種完整編碼到 fixed 表中或是調整優先順序？

**Comment by ksqsf** [comment]
總的來說是設計如此，不是 bug 也不是限制。

1. 設計目標是「能理解爲純雙拼時就理解爲純雙拼」，從而完全兼容雙拼用法。所以在輸入單字時，需要增加一個補碼，即 `uibgo` 或 `uibg/`，與詞語、句子區分開來。
2. fixed 僅用於「字詞模式」和「魔然」的簡碼輸出（帶 ⚡ 標記），這樣在輸入 uib 時，首選永遠是「實」。fixed 碼表在「輔篩」和「整句」中都不會用到。
3. 在「魔然」中，默認會開啓「出簡讓全」（可以關閉），也就是「因爲『實』可以用 uib 打出，所以 uibgo 會讓給另外的候選」。

邏輯還是比較複雜的 ^^b 。更詳細的解說可以參考說明書 https://rime-moran.gitbook.io/book，每個模式都不太一樣。如果有進一步的問題可以繼續留言。

**Comment by ksqsf** [comment]
另外這個截圖應該不是「輔篩模式」？輔篩的話應當有一個 comment 表示這個字匹配了輔助碼。

<img width="265" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/90755399-c94d-4461-8b18-91000f96d62e">

**Comment by eth3lbert** [comment]
> 1. 設計目標是「能理解爲純雙拼時就理解爲純雙拼」，從而完全兼容雙拼用法。所以用「魔然」和「整句」在輸入單字時，需要增加一個補碼，即 `uibgo` 或 `uibg/`，與詞語、句子區分開來

了解了，印象中有看過但忘了 😅 


> 另外這個截圖應該不是「輔篩模式」？輔篩的話應當有一個 comment 表示這個字匹配了輔助碼。
> <img alt="image" width="265" src="https://private-user-images.githubusercontent.com/23358293/344486654-90755399-c94d-4461-8b18-91000f96d62e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NzIxNjksIm5iZiI6MTcxOTc3MTg2OSwicGF0aCI6Ii8yMzM1ODI5My8zNDQ0ODY2NTQtOTA3NTUzOTktYzk0ZC00NDYxLThiMTgtOTEwMDBmOTZkNjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE4MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZDQ4ZTY2YTA0M2FlMGEwNDM4YzZhMWYwNmQxOTg2YjZkYmI3YzIzZGRhNDE4MjIyMDJiYWFlYjgyMWU0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h5eKK3nUcQU8f5Y_sXOvUkSCIp_irSXvRPYWywwSyBI">

確實，是默認模式 😅

**Comment by eth3lbert** [comment]
想在確認下，如果輸入 `uibgo` 但是結果如下：
<img width="256" alt="image" src="https://github.com/ksqsf/rime-moran/assets/2889664/17615390-d8b8-4e32-be80-2a8898e0b1a1">
這也是出簡讓全的關係嗎？

**Comment by ksqsf** [comment]
是的

**Comment by eth3lbert** [comment]
好的，感謝！
