### ISSUE TITLE
“狼来了”很常用吗？

### ISSUE THREAD

**Issue by ace-3721** [ksqsf/rime-moran#99]
本来想打出“来了”，于是输入 `lll`，却跑出来“狼来了”，而且是带闪电的，意味着改不了。我想请教一下，“狼来了”有这么高频吗？高过“来了”？

**Comment by ksqsf** [comment]
不常用。许多三码是从其他数据源和一些个人码表自动导入的，可能不太合理，欢迎提交修改建议。

**Comment by ksqsf** [comment]
> 而且是带闪电的，意味着改不了

所有东西都可以自己改。可参考 commit 09676e3 的改法。
